import { 
  Pill, Heart, Brain, Scale, Zap, Shield, Activity, 
  Microscope, Sparkles, Leaf, Droplets, Eye, Waves, 
  Target, Thermometer, Wind, Apple, Dna, FlaskConical,
  Syringe, Stethoscope, Package, Beaker, TestTube, Flame,
  Sprout, Moon, Smile, TrendingUp, Users, FileText, Upload,
  CheckCircle, Phone, BookOpen, MessageCircle, BadgeCheck
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface Category {
  id: string;
  slug: string;
  name: string;
  description: string;
  longDescription: string;
  icon: LucideIcon;
  heroImage: string;
  requiresPrescription: boolean;
  requiresLabLicense: boolean;
  targetAudience: 'patients' | 'laboratories' | 'both';
  parentCategory?: string;
  subcategories?: string[];
  legalNotice: string;
  verificationProcess: string;
  featured?: boolean;
}

export const categories: Record<string, Category> = {
  // ============= I. PRESCRIPTION DRUGS =============
  'prescription-drugs': {
    id: 'prescription-drugs',
    slug: 'prescription-drugs',
    name: 'Prescription Medications',
    description: 'FDA-approved prescription medications for various health conditions',
    longDescription: 'Access a comprehensive range of prescription medications dispensed by licensed pharmacists. All prescriptions are verified by our licensed healthcare professionals before dispensing.',
    icon: Pill,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    legalNotice: 'Valid prescription from a licensed healthcare provider required. All prescriptions are verified before dispensing.',
    verificationProcess: 'Upload your prescription or have your doctor send it directly to us. Our pharmacists will verify and contact you within 24 hours.',
    featured: true,
  },

  'pain-management': {
    id: 'pain-management',
    slug: 'pain-management',
    name: 'Pain Management & Analgesics',
    description: 'Prescription pain medications and analgesics',
    longDescription: 'Comprehensive pain management solutions including opioid and non-opioid analgesics for acute and chronic pain conditions. Dispensed under strict prescription requirements.',
    icon: Heart,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Controlled substances. Valid prescription required. May cause dependency. Use only as directed.',
    verificationProcess: 'Valid prescription required. Photo ID verification at pickup/delivery.',
    featured: true,
  },

  'anxiety-medications': {
    id: 'anxiety-medications',
    slug: 'anxiety-medications',
    name: 'Anxiety & Panic Disorder Medications',
    description: 'Anxiolytics and anti-panic medications',
    longDescription: 'Prescription medications for anxiety disorders, panic attacks, and generalized anxiety. Includes benzodiazepines, buspirone, and beta-blockers.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Schedule IV controlled substances. May cause dependency. Not for long-term use without medical supervision.',
    verificationProcess: 'Prescription verification required. Maximum 30-day supply per prescription.',
    featured: true,
  },

  'sleeping-pills': {
    id: 'sleeping-pills',
    slug: 'sleeping-pills',
    name: 'Sleeping Pills & Insomnia Medications',
    description: 'Sleep aids and insomnia treatments',
    longDescription: 'Prescription sleep medications including Z-drugs, benzodiazepine hypnotics, and melatonin receptor agonists for insomnia and sleep disturbances.',
    icon: Moon,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Schedule IV controlled substances. May cause dependency. Use short-term under medical supervision.',
    verificationProcess: 'Valid prescription required. Sleep study results may be requested.',
  },

  'antidepressants': {
    id: 'antidepressants',
    slug: 'antidepressants',
    name: 'Antidepressants & Mood Stabilizers',
    description: 'SSRIs, SNRIs, and mood stabilizers',
    longDescription: 'Prescription antidepressants including SSRIs, SNRIs, MAOIs, tricyclics, and mood stabilizers for depression, anxiety, and mood disorders.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Prescription required. May take 4-6 weeks for full effect. Do not discontinue without medical advice.',
    verificationProcess: 'Valid prescription from psychiatrist or qualified physician required.',
    featured: true,
  },

  'antipsychotics': {
    id: 'antipsychotics',
    slug: 'antipsychotics',
    name: 'Antipsychotics & Bipolar Medications',
    description: 'Antipsychotic medications for schizophrenia and bipolar disorder',
    longDescription: 'Prescription antipsychotics for schizophrenia, bipolar disorder, and severe mental health conditions. Includes both typical and atypical antipsychotics.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Prescription required. Regular psychiatric follow-up necessary. Requires monitoring for side effects.',
    verificationProcess: 'Valid prescription from psychiatrist required. Blood work monitoring may be necessary.',
  },

  'adhd-medications': {
    id: 'adhd-medications',
    slug: 'adhd-medications',
    name: 'ADHD & Focus Medications',
    description: 'ADHD stimulants and non-stimulant alternatives',
    longDescription: 'Prescription medications for ADHD including stimulants (Adderall, Ritalin, Vyvanse) and non-stimulant options (Strattera). Controlled substances requiring regular monitoring.',
    icon: Zap,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Schedule II controlled substances. High potential for abuse. Valid prescription required monthly.',
    verificationProcess: 'Valid prescription required monthly. No refills allowed on Schedule II medications.',
    featured: true,
  },

  'anticonvulsants': {
    id: 'anticonvulsants',
    slug: 'anticonvulsants',
    name: 'Anticonvulsants & Neuropathic Pain',
    description: 'Seizure medications and nerve pain treatments',
    longDescription: 'Prescription anticonvulsants for epilepsy, seizure disorders, and neuropathic pain conditions. Includes gabapentin, pregabalin, and traditional anticonvulsants.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Prescription required. Do not discontinue abruptly. Regular blood level monitoring may be necessary.',
    verificationProcess: 'Valid prescription required. Blood level monitoring for certain medications.',
  },

  'weight-loss': {
    id: 'weight-loss',
    slug: 'weight-loss',
    name: 'Weight Loss & Appetite Control',
    description: 'Prescription weight loss and appetite suppressant medications',
    longDescription: 'FDA-approved weight loss medications including GLP-1 agonists, appetite suppressants, and metabolism enhancers. Prescribed as part of comprehensive weight management.',
    icon: Scale,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Prescription required. Use only under medical supervision with diet and exercise program.',
    verificationProcess: 'Doctor consultation required. BMI and health screening necessary.',
    featured: true,
  },

  'sexual-health': {
    id: 'sexual-health',
    slug: 'sexual-health',
    name: 'Sexual Aid & Performance Medications',
    description: 'Erectile dysfunction and sexual wellness medications',
    longDescription: 'Prescription medications for erectile dysfunction, premature ejaculation, and sexual wellness. Includes PDE5 inhibitors and related treatments.',
    icon: Heart,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Prescription required. Consult your doctor about cardiovascular risks and drug interactions.',
    verificationProcess: 'Medical consultation required. Cardiac health screening may be necessary.',
    featured: true,
  },

  'hormonal-therapy': {
    id: 'hormonal-therapy',
    slug: 'hormonal-therapy',
    name: 'Hormonal & Endocrine Medications',
    description: 'Hormone therapy including transgender HRT',
    longDescription: 'Comprehensive hormone therapy including transgender hormone replacement therapy (HRT), menopause treatment, and endocrine disorder management. Testosterone, estrogen, anti-androgens, progesterone, and puberty blockers.',
    icon: Thermometer,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Prescription required. Regular hormone level monitoring necessary. Gender-affirming care provided with respect and dignity.',
    verificationProcess: 'Valid prescription from endocrinologist or qualified physician. Baseline and ongoing hormone panels required.',
    featured: true,
  },

  'cardiovascular': {
    id: 'cardiovascular',
    slug: 'cardiovascular',
    name: 'Cardiovascular & Blood Pressure',
    description: 'Heart medications and blood pressure control',
    longDescription: 'Prescription medications for hypertension, heart disease, and circulation including beta-blockers, ACE inhibitors, calcium channel blockers, and anticoagulants.',
    icon: Activity,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Prescription required. Regular monitoring of blood pressure and heart function necessary.',
    verificationProcess: 'Valid prescription required. May require periodic lab work and cardiac monitoring.',
  },

  'diabetes': {
    id: 'diabetes',
    slug: 'diabetes',
    name: 'Diabetes Medications',
    description: 'Insulin and blood sugar control medications',
    longDescription: 'Complete diabetes management medications including insulin, oral hypoglycemics, GLP-1 agonists, and blood glucose monitoring supplies.',
    icon: Droplets,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Prescription required. Regular blood glucose monitoring necessary.',
    verificationProcess: 'Valid prescription required. Insulin products require refrigeration.',
  },

  'respiratory': {
    id: 'respiratory',
    slug: 'respiratory',
    name: 'Respiratory Medications',
    description: 'Asthma, COPD, and breathing treatments',
    longDescription: 'Prescription respiratory medications including inhalers, bronchodilators, corticosteroids for asthma, COPD, and breathing disorders.',
    icon: Wind,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Prescription required. Proper inhaler technique essential for effectiveness.',
    verificationProcess: 'Valid prescription required. Pharmacist counseling on inhaler use provided.',
  },

  'gastrointestinal': {
    id: 'gastrointestinal',
    slug: 'gastrointestinal',
    name: 'Gastrointestinal & Digestive',
    description: 'Medications for digestive system disorders',
    longDescription: 'Prescription medications for IBS, IBD, GERD, ulcers, and other digestive system disorders. Includes proton pump inhibitors, antispasmodics, and inflammatory bowel treatments.',
    icon: Apple,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Prescription required. Long-term use may require periodic monitoring.',
    verificationProcess: 'Valid prescription required. Endoscopy results may be requested for certain medications.',
  },

  'antibiotics': {
    id: 'antibiotics',
    slug: 'antibiotics',
    name: 'Antibiotics & Antivirals',
    description: 'Prescription antimicrobial medications',
    longDescription: 'Prescription antibiotics and antiviral medications for bacterial and viral infections. Complete full course as directed to prevent resistance.',
    icon: Shield,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Prescription required. Complete full course even if symptoms improve. Improper use contributes to antibiotic resistance.',
    verificationProcess: 'Valid prescription required. Culture results may be necessary for certain antibiotics.',
  },

  'anti-inflammatory': {
    id: 'anti-inflammatory',
    slug: 'anti-inflammatory',
    name: 'Pain Relief & Anti-Inflammatory',
    description: 'NSAIDs and anti-inflammatory medications',
    longDescription: 'Prescription-strength NSAIDs, COX-2 inhibitors, and anti-inflammatory medications for pain and inflammation management.',
    icon: Heart,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Prescription required. May increase cardiovascular and GI risks. Use lowest effective dose.',
    verificationProcess: 'Valid prescription required. Kidney function monitoring may be necessary.',
  },

  'hrt-menopause': {
    id: 'hrt-menopause',
    slug: 'hrt-menopause',
    name: 'Hormone Replacement Therapy',
    description: 'HRT for menopause and andropause',
    longDescription: 'Hormone replacement therapy for menopause symptoms in women and testosterone replacement for men with hypogonadism.',
    icon: Thermometer,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Prescription required. Regular hormone level monitoring and health screenings necessary.',
    verificationProcess: 'Valid prescription from endocrinologist or physician. Baseline hormone panels required.',
  },

  'fertility': {
    id: 'fertility',
    slug: 'fertility',
    name: 'Fertility & Reproductive Health',
    description: 'Fertility treatments and reproductive medications',
    longDescription: 'Prescription medications for fertility enhancement, ovulation induction, and reproductive health including clomiphene, gonadotropins, and related treatments.',
    icon: Heart,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Prescription required. Use under fertility specialist supervision. Multiple pregnancy risk.',
    verificationProcess: 'Valid prescription from fertility specialist required. Regular monitoring necessary.',
  },

  'immunomodulators': {
    id: 'immunomodulators',
    slug: 'immunomodulators',
    name: 'Immune System Support',
    description: 'Immunomodulators and immune system medications',
    longDescription: 'Prescription immunomodulators for autoimmune conditions, immune deficiencies, and transplant patients. Includes biologics and immunosuppressants.',
    icon: Shield,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Prescription required. Regular monitoring for infections and side effects necessary.',
    verificationProcess: 'Valid prescription from specialist required. Regular blood work and monitoring mandatory.',
  },

  'anabolic-steroids': {
    id: 'anabolic-steroids',
    slug: 'anabolic-steroids',
    name: 'Anabolic Steroids & TRT',
    description: 'Testosterone replacement and anabolic therapy',
    longDescription: 'Prescription anabolic steroids for testosterone replacement therapy (TRT), hypogonadism treatment, and medically supervised hormone optimization. Includes testosterone cypionate, enanthate, and other anabolic agents.',
    icon: Dna,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'prescription-drugs',
    legalNotice: 'Schedule III controlled substances. Prescription required. Regular blood work and monitoring mandatory. Abuse can cause serious health risks.',
    verificationProcess: 'Valid prescription from endocrinologist or qualified physician required. Baseline hormone panel and regular monitoring necessary.',
    featured: true,
  },

  // ============= II. RESEARCH CHEMICALS =============
  'research-chemicals': {
    id: 'research-chemicals',
    slug: 'research-chemicals',
    name: 'Research Chemicals',
    description: 'Laboratory research compounds for authorized facilities',
    longDescription: 'Research chemicals for qualified laboratories and research institutions. DEA registration and proper licensing required. Not for human consumption.',
    icon: FlaskConical,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    legalNotice: 'FOR LABORATORY RESEARCH ONLY. Not for human or animal consumption. DEA license required for controlled substances.',
    verificationProcess: 'Laboratory license, DEA registration (if applicable), and research purpose documentation required.',
    featured: true,
  },

  'rc-stimulants': {
    id: 'rc-stimulants',
    slug: 'rc-stimulants',
    name: 'Research Stimulant Compounds',
    description: 'Cathinones and stimulant research chemicals',
    longDescription: 'Research-grade stimulant compounds including cathinones, amphetamine analogs, and novel stimulants for neurological and pharmacological research.',
    icon: Zap,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'FOR RESEARCH ONLY. Schedule I/II analogs. Not for human consumption. Proper disposal required.',
    verificationProcess: 'DEA Schedule I/II research license required. Research protocol documentation necessary.',
  },

  'rc-benzodiazepines': {
    id: 'rc-benzodiazepines',
    slug: 'rc-benzodiazepines',
    name: 'RC Benzodiazepines',
    description: 'Designer benzodiazepine analogs for research',
    longDescription: 'Research-grade benzodiazepines and designer analogs for GABA receptor research and neurological studies.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'FOR RESEARCH ONLY. Schedule IV analogs. Laboratory use only. Not for human consumption.',
    verificationProcess: 'Laboratory license required. Research protocol documentation necessary.',
  },

  'rc-opioids': {
    id: 'rc-opioids',
    slug: 'rc-opioids',
    name: 'RC Opioid Research Compounds',
    description: 'Novel opioid receptor modulators',
    longDescription: 'Research-grade opioid receptor agonists, antagonists, and novel analogs for pain research and pharmacological studies.',
    icon: Pill,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'Schedule I/II substances FOR RESEARCH ONLY. DEA license required. Extremely potent and dangerous. Laboratory use only.',
    verificationProcess: 'DEA Schedule I/II research license required. Secure storage protocols mandatory.',
  },

  'rc-psychedelics': {
    id: 'rc-psychedelics',
    slug: 'rc-psychedelics',
    name: 'RC Psychedelic Compounds',
    description: '2C-x, NBOMe, DOx series research chemicals',
    longDescription: 'Research-grade psychedelic phenethylamines including 2C series, NBOMe compounds, and DOx series for psychopharmacological research.',
    icon: Eye,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'Schedule I substances FOR RESEARCH ONLY. DEA Schedule I license required. Not for human consumption.',
    verificationProcess: 'DEA Schedule I research registration and IRB approval required.',
  },

  'rc-empathogens': {
    id: 'rc-empathogens',
    slug: 'rc-empathogens',
    name: 'RC Empathogen Compounds',
    description: 'MDAI, 5-APB, 6-APB and empathogen analogs',
    longDescription: 'Research-grade empathogenic compounds including benzofuran derivatives and MDMA analogs for psychiatric and neuroscience research.',
    icon: Heart,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'Schedule I analogs FOR RESEARCH ONLY. DEA license required. Not for human consumption.',
    verificationProcess: 'DEA Schedule I research license and IRB approval required.',
  },

  'rc-dissociatives': {
    id: 'rc-dissociatives',
    slug: 'rc-dissociatives',
    name: 'RC Dissociative Compounds',
    description: 'Ketamine, MXE, PCP analogs for research',
    longDescription: 'Research dissociative compounds including arylcyclohexylamine derivatives, ketamine analogs, and NMDA receptor antagonists.',
    icon: Waves,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'FOR RESEARCH ONLY. Schedule III/unscheduled analogs. Laboratory use only. Not for human consumption.',
    verificationProcess: 'Laboratory license required. Research documentation necessary.',
  },

  'rc-tryptamines': {
    id: 'rc-tryptamines',
    slug: 'rc-tryptamines',
    name: 'Tryptamines & Lysergamides',
    description: 'DMT, 5-MeO-DMT, LSD analogs',
    longDescription: 'Research-grade tryptamines and lysergamides including DMT derivatives, 5-MeO compounds, and LSD analogs for psychopharmacological research.',
    icon: Sparkles,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'Schedule I substances FOR RESEARCH ONLY. DEA Schedule I license required. Not for human consumption.',
    verificationProcess: 'DEA Schedule I research registration and detailed research protocol required.',
  },

  'rc-cannabinoids': {
    id: 'rc-cannabinoids',
    slug: 'rc-cannabinoids',
    name: 'RC Synthetic Cannabinoids',
    description: 'JWH, AB-, 5F- series cannabinoid analogs',
    longDescription: 'Research synthetic cannabinoid receptor agonists including JWH series, AB-FUBINACA, and 5F compounds for cannabinoid research.',
    icon: Leaf,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'FOR RESEARCH ONLY. Many are Schedule I. Not for human consumption. Extremely potent.',
    verificationProcess: 'Laboratory license and DEA registration required for scheduled compounds.',
  },

  'rc-analgesics': {
    id: 'rc-analgesics',
    slug: 'rc-analgesics',
    name: 'RC Novel Analgesic Compounds',
    description: 'Novel pain modulator research chemicals',
    longDescription: 'Research-grade novel analgesic compounds exploring non-opioid pain pathways and receptor modulators.',
    icon: Heart,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'FOR RESEARCH ONLY. Laboratory use only. Not for human consumption.',
    verificationProcess: 'Laboratory license required. Research protocol documentation necessary.',
  },

  'rc-peptides': {
    id: 'rc-peptides',
    slug: 'rc-peptides',
    name: 'RC Hormones & Peptides',
    description: 'Research peptides and hormone analogs',
    longDescription: 'Research-grade peptide hormones, growth factors, and synthetic peptide compounds for endocrine and metabolic research.',
    icon: Dna,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'FOR RESEARCH ONLY. Not FDA approved. Laboratory research only.',
    verificationProcess: 'Laboratory license required. Proper refrigerated storage necessary.',
  },

  'rc-antidepressants': {
    id: 'rc-antidepressants',
    slug: 'rc-antidepressants',
    name: 'RC Antidepressant Analogs',
    description: 'Novel antidepressant research compounds',
    longDescription: 'Research-grade novel antidepressant compounds exploring serotonin, dopamine, and norepinephrine pathways.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'FOR RESEARCH ONLY. Laboratory use only. Not for human consumption.',
    verificationProcess: 'Laboratory license required. Research protocol documentation necessary.',
  },

  'rc-hallucinogens': {
    id: 'rc-hallucinogens',
    slug: 'rc-hallucinogens',
    name: 'RC Dissociative & Hallucinogenic',
    description: 'Novel hallucinogenic research compounds',
    longDescription: 'Research-grade hallucinogenic and dissociative compounds for consciousness research and psychiatric studies.',
    icon: Eye,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'Schedule I substances FOR RESEARCH ONLY. DEA license required. Not for human consumption.',
    verificationProcess: 'DEA Schedule I research registration required.',
  },

  // ============= III. COGNITIVE & PERFORMANCE =============
  'cognitive-performance': {
    id: 'cognitive-performance',
    slug: 'cognitive-performance',
    name: 'Cognitive & Performance Enhancement',
    description: 'Nootropics, peptides, and performance compounds',
    longDescription: 'Cognitive enhancers, nootropics, peptides, and performance-enhancing compounds for research and authorized use.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    legalNotice: 'FOR RESEARCH USE. Some compounds may require prescription or lab authorization.',
    verificationProcess: 'Laboratory license or prescription required depending on compound classification.',
    featured: true,
  },

  'nootropics': {
    id: 'nootropics',
    slug: 'nootropics',
    name: 'Nootropics & Cognitive Enhancers',
    description: 'Racetams, modafinil, noopept, phenibut',
    longDescription: 'Research-grade cognitive enhancement compounds including racetams, modafinil analogs, and novel nootropic substances for cognitive research.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'cognitive-performance',
    legalNotice: 'FOR RESEARCH ONLY. Some compounds may be prescription medications. Not for human consumption.',
    verificationProcess: 'Laboratory license required. Prescription necessary for scheduled compounds.',
  },

  'smart-drugs': {
    id: 'smart-drugs',
    slug: 'smart-drugs',
    name: 'Smart Drugs & Study Aids',
    description: 'Cognitive enhancement and focus compounds',
    longDescription: 'Research compounds for studying cognitive enhancement, memory, focus, and learning mechanisms.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'cognitive-performance',
    legalNotice: 'FOR RESEARCH ONLY. Laboratory authorization required.',
    verificationProcess: 'Laboratory license and research protocol required.',
  },

  'peptides-sarms': {
    id: 'peptides-sarms',
    slug: 'peptides-sarms',
    name: 'Peptides & SARMs',
    description: 'RAD-140, LGD-4033, MK-677 and research peptides',
    longDescription: 'Research-grade selective androgen receptor modulators (SARMs) and peptides for muscle development research and pharmacological studies.',
    icon: Dna,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'cognitive-performance',
    legalNotice: 'FOR RESEARCH ONLY. Not FDA approved for human use. Laboratory research only.',
    verificationProcess: 'Laboratory license required. Proper storage protocols necessary.',
  },

  'energy-endurance': {
    id: 'energy-endurance',
    slug: 'energy-endurance',
    name: 'Energy & Endurance Boosters',
    description: 'Performance and endurance research compounds',
    longDescription: 'Research compounds for studying energy metabolism, endurance, and athletic performance enhancement.',
    icon: Zap,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'cognitive-performance',
    legalNotice: 'FOR RESEARCH ONLY. Not for athletic competition use.',
    verificationProcess: 'Laboratory license required.',
  },

  'focus-motivation': {
    id: 'focus-motivation',
    slug: 'focus-motivation',
    name: 'Focus & Motivation Enhancers',
    description: 'Dopaminergic and focus research compounds',
    longDescription: 'Research compounds for studying focus, motivation, and dopaminergic pathways.',
    icon: Target,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'cognitive-performance',
    legalNotice: 'FOR RESEARCH ONLY. Laboratory authorization required.',
    verificationProcess: 'Laboratory license required.',
  },

  'anti-aging': {
    id: 'anti-aging',
    slug: 'anti-aging',
    name: 'Anti-Aging & Longevity Compounds',
    description: 'NAD+, resveratrol, rapamycin research',
    longDescription: 'Research compounds for studying aging processes, cellular senescence, and longevity pathways including NAD+ precursors and mTOR inhibitors.',
    icon: Sparkles,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'cognitive-performance',
    legalNotice: 'FOR RESEARCH ONLY. Some compounds require prescription for human use.',
    verificationProcess: 'Laboratory license or prescription required depending on compound.',
  },

  'athletic-recovery': {
    id: 'athletic-recovery',
    slug: 'athletic-recovery',
    name: 'Athletic Recovery & Muscle Growth',
    description: 'Recovery and anabolic research compounds',
    longDescription: 'Research compounds for studying muscle growth, recovery, and anabolic processes.',
    icon: TrendingUp,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'cognitive-performance',
    legalNotice: 'FOR RESEARCH ONLY. Not for athletic competition use.',
    verificationProcess: 'Laboratory license required.',
  },

  'metabolic-boosters': {
    id: 'metabolic-boosters',
    slug: 'metabolic-boosters',
    name: 'Metabolic Boosters & Fat Burners',
    description: 'Metabolism and thermogenic research',
    longDescription: 'Research compounds for studying metabolic processes, thermogenesis, and fat oxidation pathways.',
    icon: Flame,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'cognitive-performance',
    legalNotice: 'FOR RESEARCH ONLY. Laboratory authorization required.',
    verificationProcess: 'Laboratory license required.',
  },

  'memory-concentration': {
    id: 'memory-concentration',
    slug: 'memory-concentration',
    name: 'Memory & Concentration Enhancers',
    description: 'Memory formation and retention research',
    longDescription: 'Research compounds for studying memory formation, retention, and concentration enhancement mechanisms.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'cognitive-performance',
    legalNotice: 'FOR RESEARCH ONLY. Laboratory authorization required.',
    verificationProcess: 'Laboratory license required.',
  },

  // ============= IV. NATURAL & ALTERNATIVE =============
  'natural-alternative': {
    id: 'natural-alternative',
    slug: 'natural-alternative',
    name: 'Natural & Alternative Medicine',
    description: 'Cannabis, herbs, and natural remedies',
    longDescription: 'Natural medicines, herbal remedies, and alternative treatments for various health conditions.',
    icon: Leaf,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    legalNotice: 'Age verification required for certain products. Comply with state and local regulations.',
    verificationProcess: 'Age verification required. Medical recommendation may be needed for cannabis products.',
    featured: true,
  },

  'cannabis-cbd': {
    id: 'cannabis-cbd',
    slug: 'cannabis-cbd',
    name: 'Cannabis & Cannabinoids',
    description: 'THC, CBD, Delta-8, HHC products',
    longDescription: 'Cannabis products including THC, CBD, Delta-8 THC, HHC, and other cannabinoid formulations for authorized use.',
    icon: Leaf,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    parentCategory: 'natural-alternative',
    legalNotice: 'Age 21+ required. Comply with state cannabis laws. Medical card may be required in some states.',
    verificationProcess: 'Age verification required. Medical cannabis card for medical program.',
  },

  'medicinal-mushrooms': {
    id: 'medicinal-mushrooms',
    slug: 'medicinal-mushrooms',
    name: 'Medicinal Mushrooms',
    description: 'Psilocybin, amanita, lion\'s mane, functional mushrooms',
    longDescription: 'Medicinal and functional mushrooms including psilocybin (where legal), amanita muscaria, lion\'s mane, reishi, and other therapeutic fungi.',
    icon: Sprout,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    parentCategory: 'natural-alternative',
    legalNotice: 'Age verification required. Psilocybin products only available where legal. Comply with local regulations.',
    verificationProcess: 'Age verification required. Some products require lab license or medical authorization.',
  },

  'herbal-anxiety-sleep': {
    id: 'herbal-anxiety-sleep',
    slug: 'herbal-anxiety-sleep',
    name: 'Herbal Anxiety & Sleep Remedies',
    description: 'Valerian, kava, ashwagandha, melatonin',
    longDescription: 'Natural herbal remedies for anxiety, stress, and sleep including valerian root, kava kava, ashwagandha, and melatonin supplements.',
    icon: Moon,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    parentCategory: 'natural-alternative',
    legalNotice: 'Dietary supplements. Not FDA approved to treat medical conditions. Consult healthcare provider.',
    verificationProcess: 'No prescription required. Age verification for certain products.',
  },

  'natural-weight-loss': {
    id: 'natural-weight-loss',
    slug: 'natural-weight-loss',
    name: 'Natural Weight Loss & Detox',
    description: 'Herbal weight loss and detoxification supplements',
    longDescription: 'Natural weight loss supplements, metabolism boosters, and detoxification products using herbal ingredients.',
    icon: Scale,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    parentCategory: 'natural-alternative',
    legalNotice: 'Dietary supplements. Results may vary. Not FDA approved. Consult healthcare provider.',
    verificationProcess: 'No prescription required.',
  },

  'herbal-libido': {
    id: 'herbal-libido',
    slug: 'herbal-libido',
    name: 'Herbal Libido & Sexual Aid',
    description: 'Natural sexual wellness and libido enhancers',
    longDescription: 'Herbal sexual wellness supplements including maca, tribulus, horny goat weed, and other natural libido enhancers.',
    icon: Heart,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    parentCategory: 'natural-alternative',
    legalNotice: 'Dietary supplements. Not FDA approved. Age 18+ required.',
    verificationProcess: 'Age verification required.',
  },

  'mood-energy-blends': {
    id: 'mood-energy-blends',
    slug: 'mood-energy-blends',
    name: 'Mood & Energy Support Blends',
    description: 'Natural mood and energy enhancement formulas',
    longDescription: 'Herbal blends for mood support, energy enhancement, and overall wellbeing using natural ingredients.',
    icon: Smile,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    parentCategory: 'natural-alternative',
    legalNotice: 'Dietary supplements. Not FDA approved to treat medical conditions.',
    verificationProcess: 'No prescription required.',
  },

  'herbal-nootropics': {
    id: 'herbal-nootropics',
    slug: 'herbal-nootropics',
    name: 'Herbal Nootropics & Focus',
    description: 'Natural cognitive enhancement herbs',
    longDescription: 'Herbal nootropics and cognitive enhancers including ginkgo biloba, bacopa, rhodiola, and other natural focus formulas.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    parentCategory: 'natural-alternative',
    legalNotice: 'Dietary supplements. Not FDA approved. Results may vary.',
    verificationProcess: 'No prescription required.',
  },

  'adaptogens': {
    id: 'adaptogens',
    slug: 'adaptogens',
    name: 'Adaptogens & Stress Relief',
    description: 'Adaptogenic herbs for stress management',
    longDescription: 'Adaptogenic herbs including ashwagandha, rhodiola, holy basil, and other stress-modulating botanicals.',
    icon: Leaf,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    parentCategory: 'natural-alternative',
    legalNotice: 'Dietary supplements. Not FDA approved. Consult healthcare provider.',
    verificationProcess: 'No prescription required.',
  },

  'natural-immune': {
    id: 'natural-immune',
    slug: 'natural-immune',
    name: 'Natural Immune Support',
    description: 'Herbal immune system boosters and antioxidants',
    longDescription: 'Natural immune system support supplements including elderberry, echinacea, vitamin C, and antioxidant formulas.',
    icon: Shield,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    parentCategory: 'natural-alternative',
    legalNotice: 'Dietary supplements. Not FDA approved to prevent or treat illness.',
    verificationProcess: 'No prescription required.',
  },

  'holistic-pain-relief': {
    id: 'holistic-pain-relief',
    slug: 'holistic-pain-relief',
    name: 'Holistic Pain & Inflammation Relief',
    description: 'Natural pain relief and anti-inflammatory herbs',
    longDescription: 'Holistic pain management and anti-inflammatory supplements using turmeric, boswellia, willow bark, and other natural ingredients.',
    icon: Heart,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    parentCategory: 'natural-alternative',
    legalNotice: 'Dietary supplements. Not FDA approved. Consult healthcare provider for chronic pain.',
    verificationProcess: 'No prescription required.',
  },

  // ============= V. SPECIALIZED & LABORATORY USE =============
  'specialized-lab': {
    id: 'specialized-lab',
    slug: 'specialized-lab',
    name: 'Specialized & Laboratory Use',
    description: 'Laboratory supplies and specialized compounds',
    longDescription: 'Specialized laboratory supplies, reagents, and compounds for authorized research facilities.',
    icon: Microscope,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    legalNotice: 'FOR LABORATORY USE ONLY. Proper licensing and authorization required.',
    verificationProcess: 'Laboratory license and institutional authorization required.',
    featured: true,
  },

  'lab-reagents': {
    id: 'lab-reagents',
    slug: 'lab-reagents',
    name: 'Laboratory Reagents & Solvents',
    description: 'Chemical reagents and laboratory solvents',
    longDescription: 'High-purity laboratory reagents, solvents, and chemicals for analytical and research applications.',
    icon: Beaker,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'specialized-lab',
    legalNotice: 'FOR LABORATORY USE ONLY. Proper handling and disposal procedures required.',
    verificationProcess: 'Laboratory license and safety training documentation required.',
  },

  'veterinary-lab': {
    id: 'veterinary-lab',
    slug: 'veterinary-lab',
    name: 'Veterinary & Animal Research',
    description: 'Veterinary medications for laboratory animals',
    longDescription: 'Veterinary medications and compounds for laboratory animal research including sedatives, anesthetics, and experimental treatments.',
    icon: Stethoscope,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'specialized-lab',
    legalNotice: 'FOR LABORATORY ANIMAL USE ONLY. IACUC approval required. Not for companion animal use.',
    verificationProcess: 'Laboratory license and IACUC protocol approval required.',
  },

  'analytical-standards': {
    id: 'analytical-standards',
    slug: 'analytical-standards',
    name: 'Analytical Standards & References',
    description: 'Reference compounds for analytical testing',
    longDescription: 'Certified reference standards and analytical standards for GC/MS, HPLC, and other analytical methods.',
    icon: TestTube,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'specialized-lab',
    legalNotice: 'FOR ANALYTICAL USE ONLY. Certificate of analysis provided.',
    verificationProcess: 'Laboratory license required.',
  },

  'custom-synthesis': {
    id: 'custom-synthesis',
    slug: 'custom-synthesis',
    name: 'Custom Synthesis Orders',
    description: 'Custom chemical synthesis services',
    longDescription: 'Custom chemical synthesis services for research institutions requiring specific compounds or analogs.',
    icon: FlaskConical,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'specialized-lab',
    legalNotice: 'FOR RESEARCH USE ONLY. Institutional authorization required.',
    verificationProcess: 'Laboratory license and research documentation required. Contact for quote.',
  },

  'bulk-rc-supply': {
    id: 'bulk-rc-supply',
    slug: 'bulk-rc-supply',
    name: 'Bulk RC Supply',
    description: 'Bulk research chemical supply for institutions',
    longDescription: 'Bulk quantities of research chemicals for qualified institutions and large-scale research projects.',
    icon: Package,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'specialized-lab',
    legalNotice: 'FOR INSTITUTIONAL RESEARCH ONLY. DEA registration required for controlled substances.',
    verificationProcess: 'Laboratory license, DEA registration (if applicable), and institutional purchase order required.',
  },

  'pharmaceutical-raw': {
    id: 'pharmaceutical-raw',
    slug: 'pharmaceutical-raw',
    name: 'Pharmaceutical Raw Materials',
    description: 'Raw pharmaceutical ingredients and intermediates',
    longDescription: 'Pharmaceutical-grade raw materials and synthetic intermediates for drug development and manufacturing.',
    icon: FlaskConical,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'specialized-lab',
    legalNotice: 'FOR MANUFACTURING AND RESEARCH USE ONLY. GMP certification may be required.',
    verificationProcess: 'Laboratory or manufacturing license required. Certificate of analysis provided.',
  },

  'peptide-synthesis': {
    id: 'peptide-synthesis',
    slug: 'peptide-synthesis',
    name: 'Peptide & Protein Synthesis',
    description: 'Peptide synthesis reagents and building blocks',
    longDescription: 'Amino acids, protected amino acids, and peptide synthesis reagents for research applications.',
    icon: Dna,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'specialized-lab',
    legalNotice: 'FOR RESEARCH USE ONLY. Not for human consumption.',
    verificationProcess: 'Laboratory license required.',
  },

  'clinical-research-kits': {
    id: 'clinical-research-kits',
    slug: 'clinical-research-kits',
    name: 'Clinical Research Kits',
    description: 'Testing kits and reagents for clinical research',
    longDescription: 'Clinical research kits, testing reagents, and diagnostic tools for clinical trials and research studies.',
    icon: Package,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'specialized-lab',
    legalNotice: 'FOR RESEARCH USE ONLY. Not for diagnostic purposes.',
    verificationProcess: 'Laboratory license and IRB approval may be required.',
  },

  'veterinary-anesthetics': {
    id: 'veterinary-anesthetics',
    slug: 'veterinary-anesthetics',
    name: 'Veterinary Anesthetics',
    description: 'Ketamine, xylazine for animal research',
    longDescription: 'Veterinary-grade anesthetics including ketamine and xylazine for laboratory animal procedures.',
    icon: Syringe,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'specialized-lab',
    legalNotice: 'FOR LABORATORY ANIMAL USE ONLY. DEA Schedule III. IACUC approval required.',
    verificationProcess: 'DEA registration, laboratory license, and IACUC protocol required.',
  },

  'sample-solutions': {
    id: 'sample-solutions',
    slug: 'sample-solutions',
    name: 'Sample Solutions & Controls',
    description: 'Quality control samples and laboratory controls',
    longDescription: 'Quality control samples, calibration standards, and laboratory control materials for analytical validation.',
    icon: TestTube,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'specialized-lab',
    legalNotice: 'FOR LABORATORY USE ONLY. Certificate of analysis provided.',
    verificationProcess: 'Laboratory license required.',
  },

  // ============= VI. WELLNESS, DETOX & RECOVERY =============
  'wellness-recovery': {
    id: 'wellness-recovery',
    slug: 'wellness-recovery',
    name: 'Wellness, Detox & Recovery',
    description: 'Detox, recovery, and wellness support supplements',
    longDescription: 'Comprehensive wellness and recovery supplements for detoxification, post-cycle therapy, and general health support.',
    icon: Heart,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    legalNotice: 'Dietary supplements. Not FDA approved. Consult healthcare provider.',
    verificationProcess: 'No prescription required for most products.',
    featured: true,
  },

  'detox-withdrawal': {
    id: 'detox-withdrawal',
    slug: 'detox-withdrawal',
    name: 'Detox & Withdrawal Support',
    description: 'Support for alcohol, opioid, and benzo withdrawal',
    longDescription: 'Supplements and support formulas for managing withdrawal symptoms from alcohol, opioids, and benzodiazepines. Medical supervision recommended.',
    icon: Shield,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    parentCategory: 'wellness-recovery',
    legalNotice: 'Dietary supplements. Not a substitute for medical detox. Seek medical supervision for withdrawal.',
    verificationProcess: 'No prescription required. Medical supervision strongly recommended.',
  },

  'liver-kidney-support': {
    id: 'liver-kidney-support',
    slug: 'liver-kidney-support',
    name: 'Liver & Kidney Detoxifiers',
    description: 'Liver and kidney health support supplements',
    longDescription: 'Liver detoxification and kidney health supplements including milk thistle, NAC, TUDCA, and organ support formulas.',
    icon: Heart,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    parentCategory: 'wellness-recovery',
    legalNotice: 'Dietary supplements. Not FDA approved. Consult healthcare provider for liver/kidney disease.',
    verificationProcess: 'No prescription required.',
  },

  'sleep-stress-recovery': {
    id: 'sleep-stress-recovery',
    slug: 'sleep-stress-recovery',
    name: 'Sleep & Stress Recovery',
    description: 'Natural sleep and stress recovery aids',
    longDescription: 'Natural supplements for sleep quality improvement and stress recovery including magnesium, GABA, l-theanine, and herbal blends.',
    icon: Moon,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    parentCategory: 'wellness-recovery',
    legalNotice: 'Dietary supplements. Not FDA approved.',
    verificationProcess: 'No prescription required.',
  },

  'anti-fatigue': {
    id: 'anti-fatigue',
    slug: 'anti-fatigue',
    name: 'Anti-Fatigue & Adrenal Support',
    description: 'Energy recovery and adrenal health supplements',
    longDescription: 'Supplements for combating fatigue and supporting adrenal function including B vitamins, adaptogens, and energy formulas.',
    icon: Zap,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    parentCategory: 'wellness-recovery',
    legalNotice: 'Dietary supplements. Not FDA approved.',
    verificationProcess: 'No prescription required.',
  },

  'immunity-vitamins': {
    id: 'immunity-vitamins',
    slug: 'immunity-vitamins',
    name: 'Immunity Boosters & Vitamins',
    description: 'Immune system support and vitamin blends',
    longDescription: 'Comprehensive immune support supplements and multivitamin blends for overall health and wellness.',
    icon: Shield,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    parentCategory: 'wellness-recovery',
    legalNotice: 'Dietary supplements. Not FDA approved to prevent or treat illness.',
    verificationProcess: 'No prescription required.',
  },

  'mental-clarity': {
    id: 'mental-clarity',
    slug: 'mental-clarity',
    name: 'Mental Clarity & Focus',
    description: 'Cognitive support and mental clarity supplements',
    longDescription: 'Natural supplements for mental clarity, focus, and cognitive function including omega-3, phosphatidylserine, and nootropic blends.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    parentCategory: 'wellness-recovery',
    legalNotice: 'Dietary supplements. Not FDA approved.',
    verificationProcess: 'No prescription required.',
  },

  'post-cycle-therapy': {
    id: 'post-cycle-therapy',
    slug: 'post-cycle-therapy',
    name: 'Post-Cycle Therapy (PCT)',
    description: 'PCT supplements for steroid users',
    longDescription: 'Post-cycle therapy supplements for individuals recovering from anabolic steroid cycles. Helps restore natural hormone production.',
    icon: Dna,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    parentCategory: 'wellness-recovery',
    legalNotice: 'Dietary supplements. Not FDA approved. Some products may require prescription.',
    verificationProcess: 'No prescription required for OTC PCT supplements. Prescription required for SERMs like Nolvadex or Clomid.',
  },

  'cellular-repair': {
    id: 'cellular-repair',
    slug: 'cellular-repair',
    name: 'Rejuvenation & Cellular Repair',
    description: 'Anti-aging and cellular health supplements',
    longDescription: 'Supplements supporting cellular health, DNA repair, and rejuvenation including NAD+ precursors, resveratrol, and antioxidants.',
    icon: Sparkles,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'both',
    parentCategory: 'wellness-recovery',
    legalNotice: 'Dietary supplements. Not FDA approved.',
    verificationProcess: 'No prescription required.',
  },
};

export const prescriptionCategories = Object.values(categories).filter(
  cat => cat.targetAudience === 'patients' && cat.requiresPrescription
);

export const researchCategories = Object.values(categories).filter(
  cat => cat.targetAudience === 'laboratories' && cat.requiresLabLicense
);

export const naturalCategories = Object.values(categories).filter(
  cat => cat.parentCategory === 'natural-alternative'
);

export const wellnessCategories = Object.values(categories).filter(
  cat => cat.parentCategory === 'wellness-recovery'
);

export const featuredCategories = Object.values(categories).filter(
  cat => cat.featured
);

export const getCategoryBySlug = (slug: string): Category | undefined => {
  return categories[slug];
};

export const getSubcategories = (parentSlug: string): Category[] => {
  return Object.values(categories).filter(cat => cat.parentCategory === parentSlug);
};

export const getAllMainCategories = (): Category[] => {
  return Object.values(categories).filter(cat => !cat.parentCategory);
};

export const getCategoryTree = () => {
  const mainCategories = getAllMainCategories();
  return mainCategories.map(main => ({
    ...main,
    subcategories: getSubcategories(main.slug)
  }));
};
