import { 
  Pill, Heart, Brain, Scale, Zap, Shield, Activity, 
  Microscope, Sparkles, Leaf, Droplets, Eye, Waves, 
  Target, Thermometer, Wind, Apple, Dna, FlaskConical,
  Syringe, Stethoscope, Package, Beaker, TestTube, Flame,
  Sprout, Moon, Smile, TrendingUp, Users, Droplet, Beef
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface Category {
  id: string;
  slug: string;
  name: string;
  description: string;
  longDescription: string;
  icon: LucideIcon;
  heroImage: string;
  requiresPrescription: boolean;
  requiresLabLicense: boolean;
  targetAudience: 'patients' | 'laboratories' | 'both';
  parentCategory?: string;
  subcategories?: string[];
  legalNotice: string;
  verificationProcess: string;
  featured?: boolean;
}

export const categories: Record<string, Category> = {
  // ============= 1. PAINKILLERS =============
  'painkillers': {
    id: 'painkillers',
    slug: 'painkillers',
    name: 'Painkillers',
    description: 'Comprehensive pain management medications from opioids to NSAIDs',
    longDescription: 'Access a full range of pain management solutions including opioid analgesics, non-opioid pain relievers, NSAIDs, neuropathic pain agents, and topical treatments. All controlled substances require valid prescription and verification.',
    icon: Heart,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    subcategories: ['opioid-analgesics', 'non-opioid-analgesics', 'nsaids', 'neuropathic-pain-agents', 'topical-analgesics'],
    legalNotice: 'Controlled substances require valid prescription. Opioids are Schedule II-IV. Risk of dependency and abuse. Use only as directed by healthcare provider.',
    verificationProcess: 'Upload prescription or have your doctor send it directly. Photo ID verification required for controlled substances. Pharmacist counseling provided.',
    featured: true,
  },

  'opioid-analgesics': {
    id: 'opioid-analgesics',
    slug: 'opioid-analgesics',
    name: 'Opioid Analgesics',
    description: 'Strong prescription opioid pain medications',
    longDescription: 'Prescription opioid pain medications including morphine, oxycodone, hydrocodone, fentanyl, tramadol, and codeine for moderate to severe pain management.',
    icon: Pill,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'painkillers',
    legalNotice: 'Schedule II controlled substances. High risk of dependency. Valid prescription required. No refills on Schedule II medications.',
    verificationProcess: 'New prescription required monthly for Schedule II. Photo ID and signature required at pickup.',
  },

  'non-opioid-analgesics': {
    id: 'non-opioid-analgesics',
    slug: 'non-opioid-analgesics',
    name: 'Non-Opioid Analgesics',
    description: 'Pain relievers without opioid dependency risk',
    longDescription: 'Non-opioid pain medications including acetaminophen, aspirin, and combination analgesics for mild to moderate pain.',
    icon: Pill,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'painkillers',
    legalNotice: 'OTC and prescription formulations available. Follow dosing instructions to avoid liver damage with acetaminophen.',
    verificationProcess: 'No prescription needed for OTC formulations. Prescription-strength requires valid prescription.',
  },

  'nsaids': {
    id: 'nsaids',
    slug: 'nsaids',
    name: 'NSAIDs',
    description: 'Non-steroidal anti-inflammatory drugs',
    longDescription: 'NSAIDs including ibuprofen, naproxen, diclofenac, celecoxib for pain and inflammation management.',
    icon: Shield,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'painkillers',
    legalNotice: 'May increase cardiovascular and GI risks. Use lowest effective dose for shortest duration.',
    verificationProcess: 'Prescription-strength requires valid prescription. OTC versions available.',
  },

  'neuropathic-pain-agents': {
    id: 'neuropathic-pain-agents',
    slug: 'neuropathic-pain-agents',
    name: 'Neuropathic Pain Agents',
    description: 'Medications for nerve pain and neuropathy',
    longDescription: 'Specialized medications for neuropathic pain including gabapentin, pregabalin, duloxetine, and amitriptyline.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'painkillers',
    legalNotice: 'Prescription required. May cause drowsiness. Do not discontinue abruptly.',
    verificationProcess: 'Valid prescription required. Titration schedule provided by pharmacist.',
  },

  'topical-analgesics': {
    id: 'topical-analgesics',
    slug: 'topical-analgesics',
    name: 'Topical Analgesics',
    description: 'Creams, patches, and gels for localized pain',
    longDescription: 'Topical pain relief including lidocaine patches, capsaicin cream, diclofenac gel, and fentanyl patches.',
    icon: Droplet,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'painkillers',
    legalNotice: 'Some formulations require prescription. Fentanyl patches are Schedule II controlled substances.',
    verificationProcess: 'Prescription required for controlled substance patches and high-strength formulations.',
  },

  // ============= 2. ANXIETY & DEPRESSION MEDICATIONS =============
  'anxiety-depression': {
    id: 'anxiety-depression',
    slug: 'anxiety-depression',
    name: 'Anxiety & Depression Medications',
    description: 'Prescription medications for mental health conditions',
    longDescription: 'Comprehensive mental health medications including benzodiazepines for anxiety, SSRIs and SNRIs for depression, mood stabilizers, and beta-blockers for performance anxiety.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    subcategories: ['benzodiazepines', 'ssris', 'snris', 'mood-stabilizers', 'beta-blockers-anxiety'],
    legalNotice: 'Prescription required. Regular psychiatric follow-up necessary. Do not discontinue abruptly without medical supervision.',
    verificationProcess: 'Valid prescription from psychiatrist or qualified physician. Regular monitoring required for controlled substances.',
    featured: true,
  },

  'benzodiazepines': {
    id: 'benzodiazepines',
    slug: 'benzodiazepines',
    name: 'Benzodiazepines',
    description: 'Anxiety relief and panic disorder medications',
    longDescription: 'Benzodiazepines including alprazolam (Xanax), diazepam (Valium), lorazepam (Ativan), clonazepam for anxiety and panic disorders.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'anxiety-depression',
    legalNotice: 'Schedule IV controlled substances. Risk of dependency. Short-term use recommended.',
    verificationProcess: 'Valid prescription required. Maximum 30-day supply. Regular monitoring for dependency.',
  },

  'ssris': {
    id: 'ssris',
    slug: 'ssris',
    name: 'SSRIs',
    description: 'Selective serotonin reuptake inhibitors',
    longDescription: 'SSRI antidepressants including sertraline, fluoxetine, citalopram, escitalopram for depression and anxiety.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'anxiety-depression',
    legalNotice: 'Prescription required. May take 4-6 weeks for full effect. Increased suicide risk in young adults initially.',
    verificationProcess: 'Valid prescription required. Regular psychiatric follow-up recommended.',
  },

  'snris': {
    id: 'snris',
    slug: 'snris',
    name: 'SNRIs',
    description: 'Serotonin-norepinephrine reuptake inhibitors',
    longDescription: 'SNRI medications including venlafaxine, duloxetine for depression, anxiety, and neuropathic pain.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'anxiety-depression',
    legalNotice: 'Prescription required. Do not discontinue abruptly - taper under medical supervision.',
    verificationProcess: 'Valid prescription required. Blood pressure monitoring may be necessary.',
  },

  'mood-stabilizers': {
    id: 'mood-stabilizers',
    slug: 'mood-stabilizers',
    name: 'Mood Stabilizers',
    description: 'Bipolar and mood disorder medications',
    longDescription: 'Mood stabilizers including lithium, valproate, lamotrigine for bipolar disorder and mood regulation.',
    icon: Activity,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'anxiety-depression',
    legalNotice: 'Prescription required. Regular blood level monitoring necessary. Therapeutic drug monitoring essential.',
    verificationProcess: 'Valid prescription from psychiatrist required. Regular lab work mandatory.',
  },

  'beta-blockers-anxiety': {
    id: 'beta-blockers-anxiety',
    slug: 'beta-blockers-anxiety',
    name: 'Beta Blockers for Anxiety',
    description: 'Performance anxiety and situational anxiety relief',
    longDescription: 'Beta-blockers including propranolol for performance anxiety, stage fright, and situational anxiety.',
    icon: Heart,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'anxiety-depression',
    legalNotice: 'Prescription required. May mask symptoms of low blood sugar in diabetics.',
    verificationProcess: 'Valid prescription required. Blood pressure and heart rate monitoring recommended.',
  },

  // ============= 3. SLEEPING & INSOMNIA MEDICATIONS =============
  'sleeping-insomnia': {
    id: 'sleeping-insomnia',
    slug: 'sleeping-insomnia',
    name: 'Sleeping & Insomnia Medications',
    description: 'Prescription sleep aids and insomnia treatments',
    longDescription: 'Comprehensive sleep medications including Z-drugs, benzodiazepine hypnotics, melatonin receptor agonists, antihistamines, and herbal sleep aids.',
    icon: Moon,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    subcategories: ['z-drugs', 'benzodiazepines-sleep', 'melatonin-agonists', 'antihistamines-sleep', 'herbal-sleep'],
    legalNotice: 'Schedule IV controlled substances. Risk of dependency with long-term use. Use short-term under medical supervision.',
    verificationProcess: 'Valid prescription required. Sleep study results may be requested for certain medications.',
    featured: true,
  },

  'z-drugs': {
    id: 'z-drugs',
    slug: 'z-drugs',
    name: 'Z-Drugs',
    description: 'Non-benzodiazepine sleep medications',
    longDescription: 'Z-drugs including zolpidem (Ambien), zopiclone, eszopiclone (Lunesta) for short-term insomnia treatment.',
    icon: Moon,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'sleeping-insomnia',
    legalNotice: 'Schedule IV controlled substances. Risk of complex sleep behaviors. Short-term use only.',
    verificationProcess: 'Valid prescription required. Maximum 30-day supply initially.',
  },

  'benzodiazepines-sleep': {
    id: 'benzodiazepines-sleep',
    slug: 'benzodiazepines-sleep',
    name: 'Benzodiazepines for Sleep',
    description: 'Benzodiazepine hypnotics',
    longDescription: 'Benzodiazepine sleep aids including temazepam, triazolam for insomnia management.',
    icon: Moon,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'sleeping-insomnia',
    legalNotice: 'Schedule IV controlled substances. High risk of dependency. Short-term use recommended.',
    verificationProcess: 'Valid prescription required. Regular monitoring for dependency.',
  },

  'melatonin-agonists': {
    id: 'melatonin-agonists',
    slug: 'melatonin-agonists',
    name: 'Melatonin Receptor Agonists',
    description: 'Circadian rhythm sleep aids',
    longDescription: 'Melatonin receptor agonists including ramelteon for circadian rhythm sleep disorders.',
    icon: Moon,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'sleeping-insomnia',
    legalNotice: 'Prescription required. Non-controlled substance. Lower abuse potential.',
    verificationProcess: 'Valid prescription required.',
  },

  'antihistamines-sleep': {
    id: 'antihistamines-sleep',
    slug: 'antihistamines-sleep',
    name: 'Antihistamines for Sleep',
    description: 'OTC and prescription antihistamine sleep aids',
    longDescription: 'Sedating antihistamines including diphenhydramine, doxylamine for occasional insomnia.',
    icon: Moon,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'sleeping-insomnia',
    legalNotice: 'OTC available. May cause next-day drowsiness. Tolerance develops with regular use.',
    verificationProcess: 'No prescription needed for OTC formulations.',
  },

  'herbal-sleep': {
    id: 'herbal-sleep',
    slug: 'herbal-sleep',
    name: 'Herbal Sleep Aids',
    description: 'Natural sleep support supplements',
    longDescription: 'Herbal sleep aids including valerian root, melatonin supplements, chamomile, passionflower.',
    icon: Leaf,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'sleeping-insomnia',
    legalNotice: 'Dietary supplements. Not FDA-approved for treating insomnia. Consult healthcare provider.',
    verificationProcess: 'No prescription needed.',
  },

  // ============= 4. WEIGHT MANAGEMENT & METABOLIC =============
  'weight-metabolic': {
    id: 'weight-metabolic',
    slug: 'weight-metabolic',
    name: 'Weight Management & Metabolic',
    description: 'Weight loss and metabolism medications',
    longDescription: 'Comprehensive weight management solutions including appetite suppressants, fat burners, GLP-1 agonists, and thyroid medications for metabolism support.',
    icon: Scale,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    subcategories: ['appetite-suppressants', 'fat-burners', 'glp1-agonists', 'thyroid-metabolism'],
    legalNotice: 'Prescription required for most formulations. Use under medical supervision with diet and exercise program.',
    verificationProcess: 'Medical consultation required. BMI and health screening necessary.',
    featured: true,
  },

  'appetite-suppressants': {
    id: 'appetite-suppressants',
    slug: 'appetite-suppressants',
    name: 'Appetite Suppressants',
    description: 'Prescription weight loss medications',
    longDescription: 'Appetite suppressant medications including phentermine, diethylpropion for weight management.',
    icon: Scale,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'weight-metabolic',
    legalNotice: 'Schedule IV controlled substances. Short-term use only. Cardiovascular monitoring required.',
    verificationProcess: 'Valid prescription required. BMI ≥30 or ≥27 with comorbidities required.',
  },

  'fat-burners': {
    id: 'fat-burners',
    slug: 'fat-burners',
    name: 'Fat Burners',
    description: 'Thermogenic and metabolic enhancers',
    longDescription: 'Fat-burning supplements and prescription formulations for enhanced metabolism and thermogenesis.',
    icon: Flame,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'weight-metabolic',
    legalNotice: 'Supplements not FDA-approved for weight loss. May contain stimulants. Consult healthcare provider.',
    verificationProcess: 'Prescription formulations require valid prescription.',
  },

  'glp1-agonists': {
    id: 'glp1-agonists',
    slug: 'glp1-agonists',
    name: 'GLP-1 Agonists',
    description: 'Injectable weight loss medications',
    longDescription: 'GLP-1 receptor agonists including semaglutide (Wegovy, Ozempic), liraglutide for weight management and diabetes.',
    icon: Syringe,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'weight-metabolic',
    legalNotice: 'Prescription required. Injectable medication. GI side effects common. Risk of thyroid tumors.',
    verificationProcess: 'Valid prescription required. Injection training provided.',
  },

  'thyroid-metabolism': {
    id: 'thyroid-metabolism',
    slug: 'thyroid-metabolism',
    name: 'Thyroid & Metabolism Boosters',
    description: 'Thyroid hormone and metabolic support',
    longDescription: 'Thyroid medications including levothyroxine, liothyronine for hypothyroidism and metabolic support.',
    icon: Thermometer,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'weight-metabolic',
    legalNotice: 'Prescription required. Regular thyroid function monitoring necessary.',
    verificationProcess: 'Valid prescription required. Thyroid panel results necessary.',
  },

  // ============= 5. SEXUAL HEALTH & PERFORMANCE =============
  'sexual-health-performance': {
    id: 'sexual-health-performance',
    slug: 'sexual-health-performance',
    name: 'Sexual Health & Performance',
    description: 'ED medications and sexual wellness products',
    longDescription: 'Comprehensive sexual health solutions including erectile dysfunction treatments, libido enhancers, female sexual aids, and testosterone therapy.',
    icon: Heart,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    subcategories: ['erectile-dysfunction', 'libido-enhancers', 'female-sexual-aids', 'testosterone-therapy'],
    legalNotice: 'Prescription required. Consult healthcare provider about cardiovascular risks and drug interactions.',
    verificationProcess: 'Medical consultation required. Cardiac health screening may be necessary.',
    featured: true,
  },

  'erectile-dysfunction': {
    id: 'erectile-dysfunction',
    slug: 'erectile-dysfunction',
    name: 'Erectile Dysfunction',
    description: 'ED medications and treatments',
    longDescription: 'PDE5 inhibitors including sildenafil (Viagra), tadalafil (Cialis), vardenafil for erectile dysfunction.',
    icon: Heart,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'sexual-health-performance',
    legalNotice: 'Prescription required. Contraindicated with nitrates. Cardiovascular screening recommended.',
    verificationProcess: 'Valid prescription required. Cardiac risk assessment may be needed.',
  },

  'libido-enhancers': {
    id: 'libido-enhancers',
    slug: 'libido-enhancers',
    name: 'Libido Enhancers',
    description: 'Sexual desire and performance boosters',
    longDescription: 'Libido enhancement supplements and medications for improved sexual desire and performance.',
    icon: Sparkles,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'sexual-health-performance',
    legalNotice: 'Most formulations are supplements. Not FDA-approved for sexual dysfunction. Consult healthcare provider.',
    verificationProcess: 'Prescription formulations require valid prescription.',
  },

  'female-sexual-aids': {
    id: 'female-sexual-aids',
    slug: 'female-sexual-aids',
    name: 'Female Sexual Aids',
    description: 'Women\'s sexual health medications',
    longDescription: 'Medications for female sexual dysfunction including flibanserin (Addyi), bremelanotide (Vyleesi).',
    icon: Heart,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'sexual-health-performance',
    legalNotice: 'Prescription required. May cause low blood pressure and fainting. Alcohol contraindicated.',
    verificationProcess: 'Valid prescription required. Specific counseling required for some medications.',
  },

  'testosterone-therapy': {
    id: 'testosterone-therapy',
    slug: 'testosterone-therapy',
    name: 'Testosterone Therapy',
    description: 'TRT for hypogonadism and low testosterone',
    longDescription: 'Testosterone replacement therapy including injections, gels, patches for male hypogonadism.',
    icon: Dna,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'sexual-health-performance',
    legalNotice: 'Schedule III controlled substance. Prescription required. Regular monitoring necessary. Cardiovascular risks.',
    verificationProcess: 'Valid prescription from endocrinologist or physician. Baseline testosterone levels required.',
  },

  // ============= 6. HORMONAL & ENDOCRINE THERAPIES =============
  'hormonal-endocrine': {
    id: 'hormonal-endocrine',
    slug: 'hormonal-endocrine',
    name: 'Hormonal & Endocrine Therapies',
    description: 'HRT and endocrine disorder medications',
    longDescription: 'Comprehensive hormone therapy including HRT for menopause, contraceptives, transgender hormone therapy, and specialized endocrine treatments.',
    icon: Thermometer,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    subcategories: ['hrt', 'contraceptives', 'transgender-hrt', 'menopause-therapy'],
    legalNotice: 'Prescription required. Regular hormone monitoring necessary. Gender-affirming care provided with dignity and respect.',
    verificationProcess: 'Valid prescription from endocrinologist or qualified physician. Baseline hormone panels required.',
    featured: true,
  },

  'hrt': {
    id: 'hrt',
    slug: 'hrt',
    name: 'Hormone Replacement Therapy',
    description: 'Comprehensive HRT for various conditions',
    longDescription: 'Hormone replacement therapy including estrogen, progesterone, testosterone for various endocrine conditions.',
    icon: Thermometer,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'hormonal-endocrine',
    legalNotice: 'Prescription required. Regular hormone level monitoring and health screenings necessary.',
    verificationProcess: 'Valid prescription required. Baseline and ongoing hormone panels mandatory.',
  },

  'contraceptives': {
    id: 'contraceptives',
    slug: 'contraceptives',
    name: 'Contraceptives',
    description: 'Birth control and family planning medications',
    longDescription: 'Oral contraceptives, patches, rings, and emergency contraception for family planning.',
    icon: Shield,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'hormonal-endocrine',
    legalNotice: 'Prescription required. Increased risk of blood clots, stroke, and heart attack in certain populations.',
    verificationProcess: 'Valid prescription required. Blood pressure screening recommended.',
  },

  'transgender-hrt': {
    id: 'transgender-hrt',
    slug: 'transgender-hrt',
    name: 'Transgender Hormonal Therapy',
    description: 'Gender-affirming hormone therapy',
    longDescription: 'Comprehensive transgender hormone therapy including estrogen, testosterone, anti-androgens, and puberty blockers for gender-affirming care.',
    icon: Heart,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'hormonal-endocrine',
    legalNotice: 'Prescription required. Gender-affirming care provided with respect and dignity. Regular monitoring necessary.',
    verificationProcess: 'Valid prescription from endocrinologist or gender specialist. Baseline labs and ongoing monitoring required.',
  },

  'menopause-therapy': {
    id: 'menopause-therapy',
    slug: 'menopause-therapy',
    name: 'Menopause Therapy',
    description: 'HRT for menopause symptom management',
    longDescription: 'Menopause hormone therapy including estrogen, progesterone combinations for hot flashes, night sweats, and other menopausal symptoms.',
    icon: Thermometer,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'hormonal-endocrine',
    legalNotice: 'Prescription required. Increased risk of breast cancer, cardiovascular events with long-term use.',
    verificationProcess: 'Valid prescription required. Mammogram and health screening recommended.',
  },

  // ============= 7. NEUROLOGICAL & COGNITIVE ENHANCERS =============
  'neurological-cognitive': {
    id: 'neurological-cognitive',
    slug: 'neurological-cognitive',
    name: 'Neurological & Cognitive Enhancers',
    description: 'ADHD medications, nootropics, and cognitive boosters',
    longDescription: 'Comprehensive cognitive enhancement including ADHD stimulants, nootropics, memory enhancers, and focus/energy boosters for improved mental performance.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    subcategories: ['adhd-medications', 'nootropics', 'memory-enhancers', 'focus-energy'],
    legalNotice: 'ADHD medications are Schedule II controlled substances. High abuse potential. Valid prescription required monthly.',
    verificationProcess: 'New prescription required monthly for Schedule II stimulants. ADHD diagnosis documentation may be requested.',
    featured: true,
  },

  'adhd-medications': {
    id: 'adhd-medications',
    slug: 'adhd-medications',
    name: 'ADHD Medications',
    description: 'Stimulant and non-stimulant ADHD treatments',
    longDescription: 'ADHD medications including amphetamine salts (Adderall), methylphenidate (Ritalin), lisdexamfetamine (Vyvanse), atomoxetine.',
    icon: Zap,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'neurological-cognitive',
    legalNotice: 'Schedule II controlled substances. No refills allowed. High abuse potential. Cardiovascular screening recommended.',
    verificationProcess: 'New prescription required monthly. Photo ID verification required.',
  },

  'nootropics': {
    id: 'nootropics',
    slug: 'nootropics',
    name: 'Nootropics',
    description: 'Cognitive enhancement supplements',
    longDescription: 'Nootropic supplements including racetams, modafinil, armodafinil, phenibut for cognitive enhancement.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'neurological-cognitive',
    legalNotice: 'Most nootropics are supplements or prescription medications. Modafinil requires prescription.',
    verificationProcess: 'Prescription medications require valid prescription. Supplements available OTC.',
  },

  'memory-enhancers': {
    id: 'memory-enhancers',
    slug: 'memory-enhancers',
    name: 'Memory Enhancers',
    description: 'Memory and learning support supplements',
    longDescription: 'Memory enhancement supplements including choline, bacopa monnieri, ginkgo biloba, phosphatidylserine.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'neurological-cognitive',
    legalNotice: 'Dietary supplements. Not FDA-approved for memory enhancement. Efficacy varies.',
    verificationProcess: 'No prescription needed for supplements.',
  },

  'focus-energy': {
    id: 'focus-energy',
    slug: 'focus-energy',
    name: 'Focus & Energy Boosters',
    description: 'Mental energy and concentration support',
    longDescription: 'Focus and energy supplements including caffeine, l-theanine, rhodiola, ginseng for mental performance.',
    icon: Zap,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'neurological-cognitive',
    legalNotice: 'Dietary supplements. May contain stimulants. Consult healthcare provider if sensitive to caffeine.',
    verificationProcess: 'No prescription needed.',
  },

  // ============= 8. RESEARCH CHEMICALS =============
  'research-chemicals': {
    id: 'research-chemicals',
    slug: 'research-chemicals',
    name: 'Research Chemicals',
    description: 'Laboratory research compounds for authorized facilities',
    longDescription: 'Research chemicals for licensed laboratories only including psychedelics, stimulant compounds, empathogens, dissociatives, cannabinoid research compounds, benzodiazepine analogs, synthetic opioids, and research peptides. Strict licensing and documentation required.',
    icon: FlaskConical,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    subcategories: ['psychedelics-rc', 'stimulant-rc', 'empathogens-rc', 'dissociatives-rc', 'cannabinoid-rc', 'benzodiazepine-rc', 'synthetic-opioid-rc', 'research-peptides'],
    legalNotice: 'LABORATORY USE ONLY. Valid laboratory license and DEA registration required. Not for human consumption. Controlled substance analogs.',
    verificationProcess: 'DEA license verification required. Laboratory credentials and end-use statement mandatory. Material Safety Data Sheets provided.',
    featured: true,
  },

  'psychedelics-rc': {
    id: 'psychedelics-rc',
    slug: 'psychedelics-rc',
    name: 'Psychedelic Research Compounds',
    description: 'Psychedelic analogs for laboratory research',
    longDescription: 'Psychedelic research compounds including tryptamines, lysergamides, phenethylamines for authorized research.',
    icon: Beaker,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'LABORATORY USE ONLY. Schedule I analog substances. DEA Schedule I license required.',
    verificationProcess: 'DEA Schedule I license verification mandatory. Research protocol required.',
  },

  'stimulant-rc': {
    id: 'stimulant-rc',
    slug: 'stimulant-rc',
    name: 'Stimulant Research Compounds',
    description: 'Cathinone and stimulant analogs',
    longDescription: 'Stimulant research chemicals including cathinone derivatives for laboratory research purposes.',
    icon: Zap,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'LABORATORY USE ONLY. Controlled substance analogs. Valid laboratory license required.',
    verificationProcess: 'Laboratory license and DEA registration verification required.',
  },

  'empathogens-rc': {
    id: 'empathogens-rc',
    slug: 'empathogens-rc',
    name: 'Empathogen Research Compounds',
    description: 'MDMA analogs and entactogen research',
    longDescription: 'Empathogen research compounds including substituted amphetamines for authorized laboratory research.',
    icon: Heart,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'LABORATORY USE ONLY. Schedule I analogs. DEA licensing required.',
    verificationProcess: 'DEA Schedule I license verification mandatory.',
  },

  'dissociatives-rc': {
    id: 'dissociatives-rc',
    slug: 'dissociatives-rc',
    name: 'Dissociative Research Compounds',
    description: 'Ketamine and PCP analogs',
    longDescription: 'Dissociative research compounds including arylcyclohexylamine derivatives for laboratory research.',
    icon: Waves,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'LABORATORY USE ONLY. Controlled substance analogs. Laboratory license required.',
    verificationProcess: 'Laboratory credentials and DEA registration verification required.',
  },

  'cannabinoid-rc': {
    id: 'cannabinoid-rc',
    slug: 'cannabinoid-rc',
    name: 'Cannabinoid Research Compounds',
    description: 'Synthetic cannabinoid research',
    longDescription: 'Synthetic cannabinoid research compounds for authorized laboratory cannabinoid receptor research.',
    icon: Leaf,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'LABORATORY USE ONLY. Schedule I analogs in most jurisdictions. Laboratory license required.',
    verificationProcess: 'Laboratory license and research protocol verification required.',
  },

  'benzodiazepine-rc': {
    id: 'benzodiazepine-rc',
    slug: 'benzodiazepine-rc',
    name: 'Benzodiazepine Analogs (RC)',
    description: 'Thienodiazepine and benzodiazepine analogs',
    longDescription: 'Benzodiazepine analog research compounds including thienodiazepines and fluorinated analogs for authorized laboratory research.',
    icon: Pill,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'LABORATORY USE ONLY. Controlled substance analogs. Valid laboratory license and DEA registration required.',
    verificationProcess: 'Laboratory license and DEA registration verification required. Research protocol mandatory.',
  },

  'synthetic-opioid-rc': {
    id: 'synthetic-opioid-rc',
    slug: 'synthetic-opioid-rc',
    name: 'Synthetic Opioid Research Compounds',
    description: 'Novel synthetic opioid analogs for research',
    longDescription: 'Synthetic opioid research compounds for authorized laboratory pharmacology and toxicology research. Extreme caution and highest security protocols required.',
    icon: Syringe,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'LABORATORY USE ONLY. Schedule I/II analogs. DEA Schedule I/II license required. Extreme respiratory hazard. Fentanyl-level security protocols mandatory.',
    verificationProcess: 'DEA Schedule I/II license verification mandatory. High-security research facility required. Narcan availability required on-site.',
  },

  'research-peptides': {
    id: 'research-peptides',
    slug: 'research-peptides',
    name: 'Research Peptides',
    description: 'Lab-grade peptides for scientific studies',
    longDescription: 'High-purity research-grade peptides for authorized laboratory biochemistry, pharmacology, and molecular biology research.',
    icon: TestTube,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'research-chemicals',
    legalNotice: 'LABORATORY USE ONLY. For in vitro research purposes. Not for human or veterinary use. Laboratory license required.',
    verificationProcess: 'Laboratory license verification required. Research protocol and end-use certification mandatory.',
  },

  // ============= 9. CANNABIS & CANNABINOID PRODUCTS =============
  'cannabis-cannabinoids': {
    id: 'cannabis-cannabinoids',
    slug: 'cannabis-cannabinoids',
    name: 'Cannabis & Cannabinoid Products',
    description: 'Medical cannabis and CBD products',
    longDescription: 'Medical cannabis products, CBD oils, THC edibles, vape cartridges, and hemp extracts where legally permitted.',
    icon: Leaf,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    subcategories: ['medical-cannabis', 'cbd-oils', 'thc-edibles', 'vape-cartridges', 'hemp-extracts'],
    legalNotice: 'Medical cannabis card or prescription required where legal. State-specific regulations apply. Age verification required.',
    verificationProcess: 'Medical cannabis card or prescription verification. Age 21+ or 18+ with medical card. State residency may be required.',
    featured: true,
  },

  'medical-cannabis': {
    id: 'medical-cannabis',
    slug: 'medical-cannabis',
    name: 'Medical Cannabis',
    description: 'Pharmaceutical-grade cannabis flower and extracts',
    longDescription: 'Medical-grade cannabis flower, concentrates, and extracts for qualifying medical conditions.',
    icon: Leaf,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'cannabis-cannabinoids',
    legalNotice: 'Medical cannabis card required. Schedule I federally. State-legal only. Age and residency restrictions apply.',
    verificationProcess: 'Valid medical cannabis card verification required. Age 18+ with medical card.',
  },

  'cbd-oils': {
    id: 'cbd-oils',
    slug: 'cbd-oils',
    name: 'CBD Oils',
    description: 'Hemp-derived CBD oil products',
    longDescription: 'CBD oil tinctures, softgels, and topicals derived from hemp with <0.3% THC.',
    icon: Droplet,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'cannabis-cannabinoids',
    legalNotice: 'Hemp-derived CBD legal federally. Not FDA-approved for medical use. Age 18+ recommended.',
    verificationProcess: 'No prescription needed for hemp-derived CBD. Age verification recommended.',
  },

  'thc-edibles': {
    id: 'thc-edibles',
    slug: 'thc-edibles',
    name: 'THC Edibles',
    description: 'Cannabis-infused edible products',
    longDescription: 'THC-infused gummies, chocolates, beverages, and other edible cannabis products.',
    icon: Apple,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'cannabis-cannabinoids',
    legalNotice: 'Medical cannabis card or adult-use legal status required. State-specific regulations. Age 21+ or 18+ with medical card.',
    verificationProcess: 'Medical cannabis card or age 21+ in legal states. State residency may be required.',
  },

  'vape-cartridges': {
    id: 'vape-cartridges',
    slug: 'vape-cartridges',
    name: 'Vape Cartridges',
    description: 'Cannabis vaporizer cartridges',
    longDescription: 'THC and CBD vaporizer cartridges, disposable vapes, and vaporizer hardware.',
    icon: Wind,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'cannabis-cannabinoids',
    legalNotice: 'Medical cannabis card required for THC products. Age 21+ or 18+ with medical card. State regulations apply.',
    verificationProcess: 'Medical cannabis card verification for THC. Age verification required.',
  },

  'hemp-extracts': {
    id: 'hemp-extracts',
    slug: 'hemp-extracts',
    name: 'Hemp Extracts',
    description: 'Full-spectrum and broad-spectrum hemp',
    longDescription: 'Hemp-derived full-spectrum, broad-spectrum, and isolate extracts and products.',
    icon: Leaf,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'cannabis-cannabinoids',
    legalNotice: 'Hemp-derived products legal federally if <0.3% THC. Not FDA-approved. Age 18+ recommended.',
    verificationProcess: 'No prescription needed. Age verification recommended.',
  },

  // ============= 10. SYRUP LEAN & COUGH FORMULATIONS =============
  'syrup-cough': {
    id: 'syrup-cough',
    slug: 'syrup-cough',
    name: 'Syrup Lean & Cough Formulations',
    description: 'Prescription cough syrups and formulations',
    longDescription: 'Prescription codeine-based syrups, promethazine formulations, and non-narcotic cough medications for respiratory symptoms.',
    icon: Droplets,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    subcategories: ['codeine-syrups', 'promethazine', 'non-narcotic-cough'],
    legalNotice: 'Schedule III/V controlled substances. Valid prescription required. High abuse potential. Not for recreational use.',
    verificationProcess: 'Valid prescription required. Photo ID verification. Quantity limits enforced.',
    featured: false,
  },

  'codeine-syrups': {
    id: 'codeine-syrups',
    slug: 'codeine-syrups',
    name: 'Codeine-based Syrups',
    description: 'Prescription codeine cough suppressants',
    longDescription: 'Codeine-promethazine and codeine combination cough syrups for severe cough.',
    icon: Droplets,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'syrup-cough',
    legalNotice: 'Schedule V controlled substances. High abuse potential. Valid prescription required. Quantity limits enforced.',
    verificationProcess: 'Valid prescription required. Photo ID and age verification mandatory.',
  },

  'promethazine': {
    id: 'promethazine',
    slug: 'promethazine',
    name: 'Promethazine Formulations',
    description: 'Antihistamine and antiemetic syrups',
    longDescription: 'Promethazine syrups and formulations for nausea, vomiting, and allergic reactions.',
    icon: Droplet,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'syrup-cough',
    legalNotice: 'Prescription required. May cause severe drowsiness. Not recommended for children under 2.',
    verificationProcess: 'Valid prescription required.',
  },

  'non-narcotic-cough': {
    id: 'non-narcotic-cough',
    slug: 'non-narcotic-cough',
    name: 'Non-narcotic Cough Syrups',
    description: 'OTC and prescription cough medications',
    longDescription: 'Non-narcotic cough syrups including dextromethorphan, guaifenesin formulations.',
    icon: Droplets,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'syrup-cough',
    legalNotice: 'OTC and prescription formulations available. Follow dosing instructions.',
    verificationProcess: 'Prescription-strength requires valid prescription. OTC available.',
  },

  // ============= 11. PSYCHEDELICS & MUSHROOMS =============
  'psychedelics-mushrooms': {
    id: 'psychedelics-mushrooms',
    slug: 'psychedelics-mushrooms',
    name: 'Psychedelics & Mushrooms',
    description: 'Clinical psychedelic therapy compounds',
    longDescription: 'Psychedelic compounds for authorized clinical research and therapy including psilocybin, LSD, DMT, mescaline, and ayahuasca where legally permitted.',
    icon: Sparkles,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: true,
    targetAudience: 'both',
    subcategories: ['psilocybin', 'lsd', 'dmt', 'mescaline', 'ayahuasca'],
    legalNotice: 'Schedule I controlled substances federally. Clinical trials and approved therapy programs only. DEA Schedule I license required for research.',
    verificationProcess: 'Clinical trial enrollment or therapy program verification required. DEA licensing for research use.',
    featured: false,
  },

  'psilocybin': {
    id: 'psilocybin',
    slug: 'psilocybin',
    name: 'Psilocybin',
    description: 'Psilocybin therapy and research',
    longDescription: 'Psilocybin for approved clinical trials, therapy programs, and authorized research.',
    icon: Sprout,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: true,
    targetAudience: 'both',
    parentCategory: 'psychedelics-mushrooms',
    legalNotice: 'Schedule I federally. Clinical trials and approved therapy only. Decriminalized in some jurisdictions.',
    verificationProcess: 'Clinical trial enrollment or therapy program verification. DEA license for research.',
  },

  'lsd': {
    id: 'lsd',
    slug: 'lsd',
    name: 'LSD',
    description: 'LSD research and clinical trials',
    longDescription: 'LSD for authorized clinical research and approved therapeutic programs.',
    icon: Eye,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'psychedelics-mushrooms',
    legalNotice: 'Schedule I controlled substance. DEA Schedule I license required. Research and clinical trials only.',
    verificationProcess: 'DEA Schedule I license verification mandatory. Research protocol required.',
  },

  'dmt': {
    id: 'dmt',
    slug: 'dmt',
    name: 'DMT',
    description: 'DMT research compounds',
    longDescription: 'N,N-DMT and 5-MeO-DMT for authorized research and clinical trials.',
    icon: Waves,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'psychedelics-mushrooms',
    legalNotice: 'Schedule I controlled substances. DEA license required. Research use only.',
    verificationProcess: 'DEA Schedule I license verification required.',
  },

  'mescaline': {
    id: 'mescaline',
    slug: 'mescaline',
    name: 'Mescaline',
    description: 'Mescaline research',
    longDescription: 'Mescaline and peyote alkaloids for authorized research programs.',
    icon: Target,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'psychedelics-mushrooms',
    legalNotice: 'Schedule I controlled substance. DEA license required. Religious exemptions exist for Native American Church.',
    verificationProcess: 'DEA Schedule I license verification required.',
  },

  'ayahuasca': {
    id: 'ayahuasca',
    slug: 'ayahuasca',
    name: 'Ayahuasca',
    description: 'Ayahuasca components and research',
    longDescription: 'Ayahuasca components (DMT, harmala alkaloids) for research and approved religious use.',
    icon: Leaf,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'psychedelics-mushrooms',
    legalNotice: 'DMT is Schedule I. Religious exemptions exist. Research requires DEA licensing.',
    verificationProcess: 'DEA license for research. Religious organization documentation for ceremonial use.',
  },

  // ============= 12. OPIOIDS & CONTROLLED PAIN THERAPY =============
  'opioids-controlled': {
    id: 'opioids-controlled',
    slug: 'opioids-controlled',
    name: 'Opioids & Controlled Pain Therapy',
    description: 'Controlled opioid medications for pain management',
    longDescription: 'Prescription opioid pain management including strong opioids, moderate opioids, partial agonists, and antagonists for pain and addiction treatment.',
    icon: Pill,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    subcategories: ['strong-opioids', 'moderate-opioids', 'partial-agonists', 'antagonists'],
    legalNotice: 'Schedule II-IV controlled substances. High risk of dependency and overdose. Valid prescription required. Naloxone co-prescribing recommended.',
    verificationProcess: 'Valid prescription required. Photo ID verification. Prescription monitoring program check. Pain management agreement may be required.',
    featured: false,
  },

  'strong-opioids': {
    id: 'strong-opioids',
    slug: 'strong-opioids',
    name: 'Strong Opioids',
    description: 'High-potency opioid analgesics',
    longDescription: 'Strong opioids including morphine, oxycodone, hydromorphone, fentanyl for severe pain.',
    icon: Syringe,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'opioids-controlled',
    legalNotice: 'Schedule II controlled substances. Extreme overdose risk. No refills allowed. Monthly prescriptions only.',
    verificationProcess: 'Valid prescription required monthly. Photo ID mandatory. Pain management contract required.',
  },

  'moderate-opioids': {
    id: 'moderate-opioids',
    slug: 'moderate-opioids',
    name: 'Moderate Opioids',
    description: 'Moderate-strength opioid medications',
    longDescription: 'Moderate opioids including hydrocodone combinations, codeine, tramadol for moderate pain.',
    icon: Pill,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'opioids-controlled',
    legalNotice: 'Schedule II-IV controlled substances. Risk of dependency. Valid prescription required.',
    verificationProcess: 'Valid prescription required. Photo ID verification for Schedule II.',
  },

  'partial-agonists': {
    id: 'partial-agonists',
    slug: 'partial-agonists',
    name: 'Partial Agonists',
    description: 'Buprenorphine for pain and addiction',
    longDescription: 'Partial opioid agonists including buprenorphine for pain management and opioid use disorder.',
    icon: Shield,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'opioids-controlled',
    legalNotice: 'Schedule III controlled substance. Requires X-waiver for addiction treatment. Lower overdose risk than full agonists.',
    verificationProcess: 'Valid prescription from X-waivered provider for addiction treatment. Regular prescription for pain.',
  },

  'antagonists': {
    id: 'antagonists',
    slug: 'antagonists',
    name: 'Opioid Antagonists',
    description: 'Naloxone and naltrexone',
    longDescription: 'Opioid antagonists including naloxone for overdose reversal and naltrexone for addiction treatment.',
    icon: Shield,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'opioids-controlled',
    legalNotice: 'Prescription required. Naloxone available without prescription in many states. Life-saving overdose reversal agent.',
    verificationProcess: 'Prescription required. Over-the-counter naloxone available in many jurisdictions.',
  },

  // ============= 13. STEROIDS & PERFORMANCE ENHANCERS =============
  'steroids-performance': {
    id: 'steroids-performance',
    slug: 'steroids-performance',
    name: 'Steroids & Performance Enhancers',
    description: 'Anabolic steroids and performance enhancement',
    longDescription: 'Prescription anabolic steroids, corticosteroids, peptides, and SARMs for medical use and authorized research.',
    icon: Dna,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'both',
    subcategories: ['anabolic-steroids', 'corticosteroids', 'peptides', 'sarms'],
    legalNotice: 'Schedule III controlled substances (anabolic steroids). Prescription required. Serious health risks with abuse. Regular monitoring necessary.',
    verificationProcess: 'Valid prescription from endocrinologist or qualified physician. Baseline labs required. Regular monitoring mandatory.',
    featured: true,
  },

  'anabolic-steroids': {
    id: 'anabolic-steroids',
    slug: 'anabolic-steroids',
    name: 'Anabolic Steroids',
    description: 'Testosterone and anabolic agents',
    longDescription: 'Anabolic steroids including testosterone, nandrolone, oxandrolone for TRT and medical conditions.',
    icon: Beef,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'steroids-performance',
    legalNotice: 'Schedule III controlled substances. Prescription required. Cardiovascular risks. Liver toxicity with oral steroids.',
    verificationProcess: 'Valid prescription required. Baseline hormone panel and regular monitoring necessary.',
  },

  'corticosteroids': {
    id: 'corticosteroids',
    slug: 'corticosteroids',
    name: 'Corticosteroids',
    description: 'Anti-inflammatory steroid medications',
    longDescription: 'Corticosteroids including prednisone, prednisolone, dexamethasone for inflammatory conditions.',
    icon: Shield,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'steroids-performance',
    legalNotice: 'Prescription required. Not controlled substances. Do not discontinue abruptly. Long-term use requires monitoring.',
    verificationProcess: 'Valid prescription required. Bone density monitoring for long-term use.',
  },

  'peptides': {
    id: 'peptides',
    slug: 'peptides',
    name: 'Peptides',
    description: 'Research and therapeutic peptides',
    longDescription: 'Peptides including BPC-157, TB-500, growth hormone secretagogues for research and medical use.',
    icon: Microscope,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'both',
    parentCategory: 'steroids-performance',
    legalNotice: 'Research use only for most peptides. Not FDA-approved. Prescription required for approved peptides.',
    verificationProcess: 'Laboratory license for research peptides. Prescription for approved therapeutic peptides.',
  },

  'sarms': {
    id: 'sarms',
    slug: 'sarms',
    name: 'SARMs',
    description: 'Selective androgen receptor modulators',
    longDescription: 'SARMs including RAD-140, LGD-4033, YK-11 for research purposes.',
    icon: Target,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: true,
    targetAudience: 'laboratories',
    parentCategory: 'steroids-performance',
    legalNotice: 'Research chemicals only. Not FDA-approved. Not for human consumption. Laboratory use only.',
    verificationProcess: 'Laboratory license verification required. Research protocol documentation.',
  },

  // ============= 14. GENERAL PRESCRIPTION MEDICATIONS =============
  'general-prescription': {
    id: 'general-prescription',
    slug: 'general-prescription',
    name: 'General Prescription Medications',
    description: 'Common prescription medications for various conditions',
    longDescription: 'General prescription medications including antibiotics, antifungals, antivirals, antihypertensives, and antidiabetics.',
    icon: Stethoscope,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    subcategories: ['antibiotics-general', 'antifungals', 'antivirals', 'antihypertensives', 'antidiabetics'],
    legalNotice: 'Valid prescription required. Complete full course of antibiotics. Do not share medications.',
    verificationProcess: 'Valid prescription from licensed healthcare provider required.',
    featured: true,
  },

  'antibiotics-general': {
    id: 'antibiotics-general',
    slug: 'antibiotics-general',
    name: 'Antibiotics',
    description: 'Prescription antibacterial medications',
    longDescription: 'Antibiotics including penicillins, cephalosporins, fluoroquinolones, macrolides for bacterial infections.',
    icon: Shield,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'general-prescription',
    legalNotice: 'Prescription required. Complete full course. Improper use contributes to antibiotic resistance.',
    verificationProcess: 'Valid prescription required. Culture results may be requested.',
  },

  'antifungals': {
    id: 'antifungals',
    slug: 'antifungals',
    name: 'Antifungals',
    description: 'Antifungal medications',
    longDescription: 'Antifungal medications including azoles, terbinafine for fungal infections.',
    icon: Shield,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'general-prescription',
    legalNotice: 'Prescription required. Liver function monitoring for systemic antifungals.',
    verificationProcess: 'Valid prescription required. Liver function tests for long-term oral use.',
  },

  'antivirals': {
    id: 'antivirals',
    slug: 'antivirals',
    name: 'Antivirals',
    description: 'Antiviral medications',
    longDescription: 'Antiviral medications including acyclovir, valacyclovir, oseltamivir for viral infections.',
    icon: Shield,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'general-prescription',
    legalNotice: 'Prescription required. Most effective when started early in infection.',
    verificationProcess: 'Valid prescription required.',
  },

  'antihypertensives': {
    id: 'antihypertensives',
    slug: 'antihypertensives',
    name: 'Antihypertensives',
    description: 'Blood pressure medications',
    longDescription: 'Blood pressure medications including ACE inhibitors, ARBs, calcium channel blockers, diuretics.',
    icon: Activity,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'general-prescription',
    legalNotice: 'Prescription required. Regular blood pressure monitoring necessary.',
    verificationProcess: 'Valid prescription required. Regular monitoring recommended.',
  },

  'antidiabetics': {
    id: 'antidiabetics',
    slug: 'antidiabetics',
    name: 'Antidiabetics',
    description: 'Diabetes medications and insulin',
    longDescription: 'Diabetes medications including metformin, insulin, GLP-1 agonists, SGLT2 inhibitors.',
    icon: Droplets,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'general-prescription',
    legalNotice: 'Prescription required. Regular blood glucose monitoring necessary.',
    verificationProcess: 'Valid prescription required. Insulin requires refrigeration.',
  },

  // ============= 15. MENTAL HEALTH & PSYCHIATRY =============
  'mental-health-psychiatry': {
    id: 'mental-health-psychiatry',
    slug: 'mental-health-psychiatry',
    name: 'Mental Health & Psychiatry',
    description: 'Psychiatric medications for mental health',
    longDescription: 'Comprehensive psychiatric medications including antipsychotics, mood stabilizers, antidepressants, and anxiolytics.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    subcategories: ['antipsychotics-psychiatric', 'mood-stabilizers-psychiatric', 'antidepressants-psychiatric', 'anxiolytics'],
    legalNotice: 'Prescription required. Regular psychiatric follow-up necessary. Do not discontinue without medical supervision.',
    verificationProcess: 'Valid prescription from psychiatrist or qualified physician. Regular monitoring required.',
    featured: true,
  },

  'antipsychotics-psychiatric': {
    id: 'antipsychotics-psychiatric',
    slug: 'antipsychotics-psychiatric',
    name: 'Antipsychotics',
    description: 'Medications for psychosis and bipolar',
    longDescription: 'Antipsychotic medications including quetiapine, olanzapine, risperidone, aripiprazole.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'mental-health-psychiatry',
    legalNotice: 'Prescription required. Regular monitoring for metabolic side effects and tardive dyskinesia.',
    verificationProcess: 'Valid prescription from psychiatrist. Regular blood work recommended.',
  },

  'mood-stabilizers-psychiatric': {
    id: 'mood-stabilizers-psychiatric',
    slug: 'mood-stabilizers-psychiatric',
    name: 'Mood Stabilizers',
    description: 'Bipolar and mood disorder treatments',
    longDescription: 'Mood stabilizers including lithium, valproate, lamotrigine, carbamazepine.',
    icon: Activity,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'mental-health-psychiatry',
    legalNotice: 'Prescription required. Therapeutic drug monitoring necessary. Regular blood levels required.',
    verificationProcess: 'Valid prescription from psychiatrist. Regular lab work mandatory.',
  },

  'antidepressants-psychiatric': {
    id: 'antidepressants-psychiatric',
    slug: 'antidepressants-psychiatric',
    name: 'Antidepressants',
    description: 'Depression and anxiety treatments',
    longDescription: 'Antidepressants including SSRIs, SNRIs, TCAs, MAOIs, and atypical antidepressants.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'mental-health-psychiatry',
    legalNotice: 'Prescription required. May take 4-6 weeks for full effect. Suicide risk monitoring initially.',
    verificationProcess: 'Valid prescription required. Regular psychiatric follow-up recommended.',
  },

  'anxiolytics': {
    id: 'anxiolytics',
    slug: 'anxiolytics',
    name: 'Anxiolytics',
    description: 'Anti-anxiety medications',
    longDescription: 'Anxiolytic medications including benzodiazepines, buspirone, hydroxyzine for anxiety disorders.',
    icon: Brain,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'mental-health-psychiatry',
    legalNotice: 'Benzodiazepines are Schedule IV controlled substances. Risk of dependency with long-term use.',
    verificationProcess: 'Valid prescription required. Regular monitoring for controlled substances.',
  },

  // ============= 16. CARDIOVASCULAR & BLOOD HEALTH =============
  'cardiovascular-blood': {
    id: 'cardiovascular-blood',
    slug: 'cardiovascular-blood',
    name: 'Cardiovascular & Blood Health',
    description: 'Heart and blood health medications',
    longDescription: 'Cardiovascular medications including blood pressure control, anticoagulants, and cholesterol management.',
    icon: Heart,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    subcategories: ['bp-control', 'anticoagulants', 'cholesterol-management'],
    legalNotice: 'Prescription required. Regular monitoring of cardiovascular and blood parameters necessary.',
    verificationProcess: 'Valid prescription required. Regular lab work and monitoring recommended.',
    featured: true,
  },

  'bp-control': {
    id: 'bp-control',
    slug: 'bp-control',
    name: 'Blood Pressure Control',
    description: 'Antihypertensive medications',
    longDescription: 'Blood pressure medications including ACE inhibitors, ARBs, beta-blockers, calcium channel blockers, diuretics.',
    icon: Activity,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'cardiovascular-blood',
    legalNotice: 'Prescription required. Regular blood pressure monitoring necessary. Do not discontinue abruptly.',
    verificationProcess: 'Valid prescription required. Blood pressure monitoring recommended.',
  },

  'anticoagulants': {
    id: 'anticoagulants',
    slug: 'anticoagulants',
    name: 'Anticoagulants',
    description: 'Blood thinners and clot prevention',
    longDescription: 'Anticoagulant medications including warfarin, DOACs (apixaban, rivaroxaban), antiplatelet agents.',
    icon: Droplets,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'cardiovascular-blood',
    legalNotice: 'Prescription required. Bleeding risk. Regular INR monitoring for warfarin. Avoid injuries.',
    verificationProcess: 'Valid prescription required. Regular blood work for warfarin.',
  },

  'cholesterol-management': {
    id: 'cholesterol-management',
    slug: 'cholesterol-management',
    name: 'Cholesterol Management',
    description: 'Statins and lipid-lowering drugs',
    longDescription: 'Cholesterol medications including statins, ezetimibe, PCSK9 inhibitors, fibrates.',
    icon: Heart,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'cardiovascular-blood',
    legalNotice: 'Prescription required. Liver function monitoring recommended. Muscle pain requires medical attention.',
    verificationProcess: 'Valid prescription required. Baseline and periodic liver function tests.',
  },

  // ============= 17. DIGESTIVE & GASTROINTESTINAL =============
  'digestive-gi': {
    id: 'digestive-gi',
    slug: 'digestive-gi',
    name: 'Digestive & Gastrointestinal',
    description: 'GI and digestive system medications',
    longDescription: 'Gastrointestinal medications including antacids, proton pump inhibitors, laxatives, and IBS treatments.',
    icon: Apple,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    subcategories: ['antacids', 'ppis', 'laxatives', 'ibs-treatments'],
    legalNotice: 'Some medications require prescription. OTC versions available for many formulations.',
    verificationProcess: 'Prescription-strength requires valid prescription. OTC available for many.',
    featured: true,
  },

  'antacids': {
    id: 'antacids',
    slug: 'antacids',
    name: 'Antacids',
    description: 'Acid relief and heartburn treatments',
    longDescription: 'Antacids and H2 blockers including calcium carbonate, famotidine, ranitidine for heartburn.',
    icon: Apple,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'digestive-gi',
    legalNotice: 'OTC available. Prescription-strength H2 blockers require prescription.',
    verificationProcess: 'No prescription needed for OTC. Prescription for high-strength formulations.',
  },

  'ppis': {
    id: 'ppis',
    slug: 'ppis',
    name: 'Proton Pump Inhibitors',
    description: 'PPI medications for acid suppression',
    longDescription: 'Proton pump inhibitors including omeprazole, pantoprazole, esomeprazole for GERD and ulcers.',
    icon: Shield,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'digestive-gi',
    legalNotice: 'OTC and prescription formulations available. Long-term use may require monitoring.',
    verificationProcess: 'Prescription-strength requires valid prescription. Low-dose OTC available.',
  },

  'laxatives': {
    id: 'laxatives',
    slug: 'laxatives',
    name: 'Laxatives',
    description: 'Constipation relief medications',
    longDescription: 'Laxatives including osmotic, stimulant, and bulk-forming agents for constipation.',
    icon: Droplet,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'digestive-gi',
    legalNotice: 'OTC available. Prolonged use not recommended without medical supervision.',
    verificationProcess: 'No prescription needed for most formulations.',
  },

  'ibs-treatments': {
    id: 'ibs-treatments',
    slug: 'ibs-treatments',
    name: 'IBS Treatments',
    description: 'Irritable bowel syndrome medications',
    longDescription: 'IBS medications including antispasmodics, rifaximin, eluxadoline for irritable bowel syndrome.',
    icon: Apple,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'digestive-gi',
    legalNotice: 'Prescription required for most IBS-specific medications.',
    verificationProcess: 'Valid prescription required. IBS diagnosis documentation may be requested.',
  },

  // ============= 18. DERMATOLOGY & SKINCARE MEDICATIONS =============
  'dermatology-skincare': {
    id: 'dermatology-skincare',
    slug: 'dermatology-skincare',
    name: 'Dermatology & Skincare Medications',
    description: 'Prescription skin treatments',
    longDescription: 'Dermatological medications including acne treatments, steroid creams, antifungal creams, and skin regeneration therapies.',
    icon: Sparkles,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    subcategories: ['acne-treatments', 'steroid-creams', 'antifungal-creams', 'skin-regeneration'],
    legalNotice: 'Prescription required for most formulations. Some OTC options available.',
    verificationProcess: 'Valid prescription from dermatologist or physician required.',
    featured: true,
  },

  'acne-treatments': {
    id: 'acne-treatments',
    slug: 'acne-treatments',
    name: 'Acne Treatments',
    description: 'Prescription acne medications',
    longDescription: 'Acne treatments including retinoids, isotretinoin, topical antibiotics, benzoyl peroxide.',
    icon: Sparkles,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'dermatology-skincare',
    legalNotice: 'Prescription required. Isotretinoin requires iPLEDGE program enrollment. Teratogenic risk.',
    verificationProcess: 'Valid prescription required. iPLEDGE enrollment for isotretinoin.',
  },

  'steroid-creams': {
    id: 'steroid-creams',
    slug: 'steroid-creams',
    name: 'Steroid Creams',
    description: 'Topical corticosteroid treatments',
    longDescription: 'Topical corticosteroids in various strengths for inflammatory skin conditions.',
    icon: Droplet,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'dermatology-skincare',
    legalNotice: 'Prescription required for mid-high potency. Low potency OTC available. Do not use on face without guidance.',
    verificationProcess: 'Valid prescription required for prescription-strength formulations.',
  },

  'antifungal-creams': {
    id: 'antifungal-creams',
    slug: 'antifungal-creams',
    name: 'Antifungal Creams',
    description: 'Topical antifungal treatments',
    longDescription: 'Topical antifungals for athlete\'s foot, ringworm, yeast infections.',
    icon: Shield,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'dermatology-skincare',
    legalNotice: 'OTC and prescription formulations available. Use full course for effectiveness.',
    verificationProcess: 'No prescription needed for OTC. Prescription for high-strength formulations.',
  },

  'skin-regeneration': {
    id: 'skin-regeneration',
    slug: 'skin-regeneration',
    name: 'Skin Regeneration Therapies',
    description: 'Anti-aging and regenerative treatments',
    longDescription: 'Skin regeneration treatments including tretinoin, growth factors, peptides for anti-aging.',
    icon: Sparkles,
    heroImage: '/placeholder.svg',
    requiresPrescription: true,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'dermatology-skincare',
    legalNotice: 'Prescription required for tretinoin and medical-grade formulations.',
    verificationProcess: 'Valid prescription from dermatologist required.',
  },

  // ============= 19. VITAMINS, SUPPLEMENTS & WELLNESS =============
  'vitamins-supplements': {
    id: 'vitamins-supplements',
    slug: 'vitamins-supplements',
    name: 'Vitamins, Supplements & Wellness',
    description: 'Nutritional supplements and wellness products',
    longDescription: 'Comprehensive vitamins, minerals, herbal extracts, and immunity boosters for optimal health and wellness.',
    icon: Apple,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    subcategories: ['multivitamins', 'mineral-supplements', 'herbal-extracts', 'immunity-boosters'],
    legalNotice: 'Dietary supplements. Not FDA-approved for disease treatment. Consult healthcare provider before starting.',
    verificationProcess: 'No prescription needed. Consultation recommended for medical conditions.',
    featured: true,
  },

  'multivitamins': {
    id: 'multivitamins',
    slug: 'multivitamins',
    name: 'Multivitamins',
    description: 'Daily multivitamin formulations',
    longDescription: 'Comprehensive multivitamin formulations for daily nutritional support.',
    icon: Pill,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'vitamins-supplements',
    legalNotice: 'Dietary supplements. Exceeding recommended doses may be harmful.',
    verificationProcess: 'No prescription needed.',
  },

  'mineral-supplements': {
    id: 'mineral-supplements',
    slug: 'mineral-supplements',
    name: 'Mineral Supplements',
    description: 'Essential mineral supplementation',
    longDescription: 'Mineral supplements including calcium, magnesium, zinc, iron for optimal health.',
    icon: Pill,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'vitamins-supplements',
    legalNotice: 'Dietary supplements. High-dose iron requires prescription in some formulations.',
    verificationProcess: 'No prescription needed for most. Prescription for high-dose formulations.',
  },

  'herbal-extracts': {
    id: 'herbal-extracts',
    slug: 'herbal-extracts',
    name: 'Herbal Extracts',
    description: 'Natural herbal supplement extracts',
    longDescription: 'Herbal extracts including ashwagandha, turmeric, ginseng, St. John\'s wort for wellness.',
    icon: Leaf,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'vitamins-supplements',
    legalNotice: 'Dietary supplements. May interact with prescription medications. Consult healthcare provider.',
    verificationProcess: 'No prescription needed. Consultation recommended.',
  },

  'immunity-boosters': {
    id: 'immunity-boosters',
    slug: 'immunity-boosters',
    name: 'Immunity Boosters',
    description: 'Immune system support supplements',
    longDescription: 'Immune support supplements including vitamin C, vitamin D, zinc, elderberry, probiotics.',
    icon: Shield,
    heroImage: '/placeholder.svg',
    requiresPrescription: false,
    requiresLabLicense: false,
    targetAudience: 'patients',
    parentCategory: 'vitamins-supplements',
    legalNotice: 'Dietary supplements. Not proven to prevent or treat diseases. Consult healthcare provider.',
    verificationProcess: 'No prescription needed.',
  },
};

// Filtered category exports
export const prescriptionCategories = Object.values(categories).filter(
  (cat) => cat.requiresPrescription && cat.targetAudience === 'patients' && !cat.parentCategory
);

export const researchCategories = Object.values(categories).filter(
  (cat) => cat.requiresLabLicense && cat.targetAudience === 'laboratories' && !cat.parentCategory
);

export const naturalCategories = Object.values(categories).filter(
  (cat) => cat.id.includes('vitamins') || cat.id.includes('herbal') || cat.id.includes('hemp')
);

export const wellnessCategories = Object.values(categories).filter(
  (cat) => cat.id.includes('wellness') || cat.id.includes('supplements') || cat.id.includes('immunity')
);

export const featuredCategories = Object.values(categories).filter(
  (cat) => cat.featured && !cat.parentCategory
);

// Utility functions
export const getCategoryBySlug = (slug: string): Category | undefined => {
  return categories[slug];
};

export const getSubcategories = (parentSlug: string): Category[] => {
  return Object.values(categories).filter(
    (cat) => cat.parentCategory === parentSlug
  );
};

export const getAllMainCategories = (): Category[] => {
  return Object.values(categories).filter((cat) => !cat.parentCategory);
};

export const getCategoryTree = () => {
  const mainCategories = getAllMainCategories();
  return mainCategories.map((mainCat) => ({
    ...mainCat,
    subcategories: getSubcategories(mainCat.slug),
  }));
};
